//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for HealthStatus.
const (
	Ok HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for Layer.
const (
	Administration         Layer = "administration"
	Applicative            Layer = "applicative"
	Business               Layer = "business"
	Ecosystem              Layer = "ecosystem"
	InfrastructureLogical  Layer = "infrastructure_logical"
	InfrastructurePhysical Layer = "infrastructure_physical"
)

// Valid indicates whether the value is a known member of the Layer enum.
func (e Layer) Valid() bool {
	switch e {
	case Administration:
		return true
	case Applicative:
		return true
	case Business:
		return true
	case Ecosystem:
		return true
	case InfrastructureLogical:
		return true
	case InfrastructurePhysical:
		return true
	default:
		return false
	}
}

// Defines values for WorkloadKind.
const (
	DaemonSet   WorkloadKind = "DaemonSet"
	Deployment  WorkloadKind = "Deployment"
	StatefulSet WorkloadKind = "StatefulSet"
)

// Valid indicates whether the value is a known member of the WorkloadKind enum.
func (e WorkloadKind) Valid() bool {
	switch e {
	case DaemonSet:
		return true
	case Deployment:
		return true
	case StatefulSet:
		return true
	default:
		return false
	}
}

// Cluster defines model for Cluster.
type Cluster struct {
	// ApiEndpoint Kubernetes API server URL (informational).
	ApiEndpoint *string    `json:"api_endpoint,omitempty"`
	CreatedAt   *time.Time `json:"created_at,omitempty"`

	// DisplayName Human-friendly label, free-form.
	DisplayName *string `json:"display_name,omitempty"`

	// Environment Free-form environment tag (e.g., dev, staging, prod).
	Environment *string             `json:"environment,omitempty"`
	Id          *openapi_types.UUID `json:"id,omitempty"`

	// KubernetesVersion Cluster API server version reported by Kubernetes (e.g. "1.29.5").
	KubernetesVersion *string `json:"kubernetes_version,omitempty"`

	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`

	// Layer Always `infrastructure_logical` for Cluster. Set by the server.
	Layer *Layer `json:"layer,omitempty"`
	Name  string `json:"name"`

	// Provider Underlying Kubernetes distribution or hosting provider.
	// Open-ended; common values: gke, eks, aks, openshift, rke, kubeadm, onprem, other.
	Provider  *string    `json:"provider,omitempty"`
	Region    *string    `json:"region,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// ClusterCreate defines model for ClusterCreate.
type ClusterCreate struct {
	// ApiEndpoint Kubernetes API server URL (informational).
	ApiEndpoint *string `json:"api_endpoint,omitempty"`

	// DisplayName Human-friendly label, free-form.
	DisplayName *string `json:"display_name,omitempty"`

	// Environment Free-form environment tag (e.g., dev, staging, prod).
	Environment *string `json:"environment,omitempty"`

	// KubernetesVersion Cluster API server version reported by Kubernetes (e.g. "1.29.5").
	KubernetesVersion *string `json:"kubernetes_version,omitempty"`

	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`

	// Name Stable slug-like identifier, unique across the CMDB.
	// Immutable after creation.
	Name string `json:"name"`

	// Provider Underlying Kubernetes distribution or hosting provider.
	// Open-ended; common values: gke, eks, aks, openshift, rke, kubeadm, onprem, other.
	Provider *string `json:"provider,omitempty"`
	Region   *string `json:"region,omitempty"`
}

// ClusterList Paged list of clusters.
type ClusterList struct {
	Items []Cluster `json:"items"`

	// NextCursor Opaque cursor to pass as `?cursor=` to fetch the next page.
	// Absent or null when no more pages remain.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// ClusterMutable Fields on a Cluster that clients may set and later update.
type ClusterMutable struct {
	// ApiEndpoint Kubernetes API server URL (informational).
	ApiEndpoint *string `json:"api_endpoint,omitempty"`

	// DisplayName Human-friendly label, free-form.
	DisplayName *string `json:"display_name,omitempty"`

	// Environment Free-form environment tag (e.g., dev, staging, prod).
	Environment *string `json:"environment,omitempty"`

	// KubernetesVersion Cluster API server version reported by Kubernetes (e.g. "1.29.5").
	KubernetesVersion *string `json:"kubernetes_version,omitempty"`

	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`

	// Provider Underlying Kubernetes distribution or hosting provider.
	// Open-ended; common values: gke, eks, aks, openshift, rke, kubeadm, onprem, other.
	Provider *string `json:"provider,omitempty"`
	Region   *string `json:"region,omitempty"`
}

// ClusterUpdate Fields on a Cluster that clients may set and later update.
type ClusterUpdate = ClusterMutable

// Health defines model for Health.
type Health struct {
	Status HealthStatus `json:"status"`

	// Version Build version of the running argosd.
	Version *string `json:"version,omitempty"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// Layer ANSSI cartography layer the asset belongs to. See ADR-0002 for the
// kind-to-layer mapping and the rationale behind the six-layer model.
type Layer string

// Namespace defines model for Namespace.
type Namespace struct {
	ClusterId openapi_types.UUID `json:"cluster_id"`
	CreatedAt *time.Time         `json:"created_at,omitempty"`

	// DisplayName Human-friendly label, free-form.
	DisplayName *string             `json:"display_name,omitempty"`
	Id          *openapi_types.UUID `json:"id,omitempty"`

	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`

	// Layer Always `infrastructure_logical` for Namespace. Set by the server.
	Layer *Layer `json:"layer,omitempty"`
	Name  string `json:"name"`

	// Phase Kubernetes namespace phase as last observed (e.g. "Active", "Terminating").
	// Open-ended to accommodate any additional phases Kubernetes introduces.
	Phase     *string    `json:"phase,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// NamespaceCreate defines model for NamespaceCreate.
type NamespaceCreate struct {
	// ClusterId Parent cluster id. Immutable after creation; the cluster must
	// already exist or the create returns 404.
	ClusterId openapi_types.UUID `json:"cluster_id"`

	// DisplayName Human-friendly label, free-form.
	DisplayName *string `json:"display_name,omitempty"`

	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`

	// Name Kubernetes namespace name (DNS-label style). Unique per cluster.
	// Immutable after creation.
	Name string `json:"name"`

	// Phase Kubernetes namespace phase as last observed (e.g. "Active", "Terminating").
	// Open-ended to accommodate any additional phases Kubernetes introduces.
	Phase *string `json:"phase,omitempty"`
}

// NamespaceList Paged list of namespaces.
type NamespaceList struct {
	Items []Namespace `json:"items"`

	// NextCursor Opaque cursor to pass as `?cursor=` to fetch the next page.
	// Absent or null when no more pages remain.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// NamespaceMutable Fields on a Namespace that clients may set and later update.
type NamespaceMutable struct {
	// DisplayName Human-friendly label, free-form.
	DisplayName *string `json:"display_name,omitempty"`

	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`

	// Phase Kubernetes namespace phase as last observed (e.g. "Active", "Terminating").
	// Open-ended to accommodate any additional phases Kubernetes introduces.
	Phase *string `json:"phase,omitempty"`
}

// NamespaceUpdate Fields on a Namespace that clients may set and later update.
type NamespaceUpdate = NamespaceMutable

// Node defines model for Node.
type Node struct {
	// Architecture CPU architecture. Open-ended; common values: amd64, arm64, ppc64le, s390x.
	Architecture *string            `json:"architecture,omitempty"`
	ClusterId    openapi_types.UUID `json:"cluster_id"`
	CreatedAt    *time.Time         `json:"created_at,omitempty"`

	// DisplayName Human-friendly label, free-form.
	DisplayName *string             `json:"display_name,omitempty"`
	Id          *openapi_types.UUID `json:"id,omitempty"`

	// KubeletVersion Kubelet git version as reported by Kubernetes (e.g. "v1.29.5").
	KubeletVersion *string `json:"kubelet_version,omitempty"`

	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`

	// Layer Always `infrastructure_physical` for Node. Set by the server.
	Layer *Layer `json:"layer,omitempty"`
	Name  string `json:"name"`

	// OsImage Node OS image string (e.g. "Ubuntu 22.04.3 LTS").
	OsImage   *string    `json:"os_image,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// NodeCreate defines model for NodeCreate.
type NodeCreate struct {
	// Architecture CPU architecture. Open-ended; common values: amd64, arm64, ppc64le, s390x.
	Architecture *string `json:"architecture,omitempty"`

	// ClusterId Parent cluster id. Immutable after creation; the cluster must
	// already exist or the create returns 404.
	ClusterId openapi_types.UUID `json:"cluster_id"`

	// DisplayName Human-friendly label, free-form.
	DisplayName *string `json:"display_name,omitempty"`

	// KubeletVersion Kubelet git version as reported by Kubernetes (e.g. "v1.29.5").
	KubeletVersion *string `json:"kubelet_version,omitempty"`

	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`

	// Name Kubernetes node name (DNS-subdomain style). Unique per cluster.
	// Immutable after creation.
	Name string `json:"name"`

	// OsImage Node OS image string (e.g. "Ubuntu 22.04.3 LTS").
	OsImage *string `json:"os_image,omitempty"`
}

// NodeList Paged list of nodes.
type NodeList struct {
	Items []Node `json:"items"`

	// NextCursor Opaque cursor to pass as `?cursor=` to fetch the next page.
	// Absent or null when no more pages remain.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// NodeMutable Fields on a Node that clients may set and later update.
type NodeMutable struct {
	// Architecture CPU architecture. Open-ended; common values: amd64, arm64, ppc64le, s390x.
	Architecture *string `json:"architecture,omitempty"`

	// DisplayName Human-friendly label, free-form.
	DisplayName *string `json:"display_name,omitempty"`

	// KubeletVersion Kubelet git version as reported by Kubernetes (e.g. "v1.29.5").
	KubeletVersion *string `json:"kubelet_version,omitempty"`

	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`

	// OsImage Node OS image string (e.g. "Ubuntu 22.04.3 LTS").
	OsImage *string `json:"os_image,omitempty"`
}

// NodeUpdate Fields on a Node that clients may set and later update.
type NodeUpdate = NodeMutable

// Pod defines model for Pod.
type Pod struct {
	CreatedAt *time.Time          `json:"created_at,omitempty"`
	Id        *openapi_types.UUID `json:"id,omitempty"`

	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`

	// Layer Always `applicative` for Pod. Set by the server.
	Layer       *Layer             `json:"layer,omitempty"`
	Name        string             `json:"name"`
	NamespaceId openapi_types.UUID `json:"namespace_id"`

	// NodeName Name of the node the pod is scheduled on.
	NodeName *string `json:"node_name,omitempty"`

	// Phase Kubernetes pod phase as last observed: Pending, Running, Succeeded,
	// Failed, or Unknown. Open-ended to accommodate any additional phases.
	Phase *string `json:"phase,omitempty"`

	// PodIp Pod IP address (IPv4 or IPv6). Informational; not validated as an
	// IP literal.
	PodIp     *string    `json:"pod_ip,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// PodCreate defines model for PodCreate.
type PodCreate struct {
	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`

	// Name Kubernetes pod name (DNS-subdomain style). Unique per namespace.
	// Immutable after creation.
	Name string `json:"name"`

	// NamespaceId Parent namespace id. Immutable after creation; the namespace
	// must already exist or the create returns 404.
	NamespaceId openapi_types.UUID `json:"namespace_id"`

	// NodeName Name of the node the pod is scheduled on.
	NodeName *string `json:"node_name,omitempty"`

	// Phase Kubernetes pod phase as last observed: Pending, Running, Succeeded,
	// Failed, or Unknown. Open-ended to accommodate any additional phases.
	Phase *string `json:"phase,omitempty"`

	// PodIp Pod IP address (IPv4 or IPv6). Informational; not validated as an
	// IP literal.
	PodIp *string `json:"pod_ip,omitempty"`
}

// PodList Paged list of pods.
type PodList struct {
	Items []Pod `json:"items"`

	// NextCursor Opaque cursor to pass as `?cursor=` to fetch the next page.
	// Absent or null when no more pages remain.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// PodMutable Fields on a Pod that clients may set and later update.
type PodMutable struct {
	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`

	// NodeName Name of the node the pod is scheduled on.
	NodeName *string `json:"node_name,omitempty"`

	// Phase Kubernetes pod phase as last observed: Pending, Running, Succeeded,
	// Failed, or Unknown. Open-ended to accommodate any additional phases.
	Phase *string `json:"phase,omitempty"`

	// PodIp Pod IP address (IPv4 or IPv6). Informational; not validated as an
	// IP literal.
	PodIp *string `json:"pod_ip,omitempty"`
}

// PodUpdate Fields on a Pod that clients may set and later update.
type PodUpdate = PodMutable

// Problem RFC 7807 problem details.
type Problem struct {
	Detail *string `json:"detail,omitempty"`

	// Errors Field-level validation errors, when applicable.
	Errors *[]struct {
		Field   string `json:"field"`
		Message string `json:"message"`
	} `json:"errors,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   int     `json:"status"`
	Title    string  `json:"title"`
	Type     string  `json:"type"`
}

// Workload defines model for Workload.
type Workload struct {
	CreatedAt *time.Time          `json:"created_at,omitempty"`
	Id        *openapi_types.UUID `json:"id,omitempty"`

	// Kind Kubernetes workload controller kind. Casing matches the `kind` field
	// Kubernetes itself emits. Additional kinds (Job, CronJob, ReplicaSet,
	// ReplicationController) may be introduced as new enum values without a
	// schema migration (see ADR-0003).
	Kind WorkloadKind `json:"kind"`

	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`

	// Layer Always `applicative` for Workload. Set by the server.
	Layer       *Layer             `json:"layer,omitempty"`
	Name        string             `json:"name"`
	NamespaceId openapi_types.UUID `json:"namespace_id"`

	// ReadyReplicas Observed ready replica count. Nullable until first status update.
	ReadyReplicas *int `json:"ready_replicas,omitempty"`

	// Replicas Desired replica count. Nullable; DaemonSet has no scalar desired count.
	Replicas *int `json:"replicas,omitempty"`

	// Spec Kind-specific fields the collector chooses to persist (e.g. strategy
	// for Deployment, service_name for StatefulSet). Open-ended; stored
	// as JSONB.
	Spec      *map[string]interface{} `json:"spec,omitempty"`
	UpdatedAt *time.Time              `json:"updated_at,omitempty"`
}

// WorkloadCreate defines model for WorkloadCreate.
type WorkloadCreate struct {
	// Kind Workload kind discriminator. Immutable after creation.
	Kind WorkloadKind `json:"kind"`

	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`

	// Name Kubernetes workload name (DNS-subdomain style). Unique per
	// (namespace, kind). Immutable after creation.
	Name string `json:"name"`

	// NamespaceId Parent namespace id. Immutable after creation; the namespace
	// must already exist or the create returns 404.
	NamespaceId openapi_types.UUID `json:"namespace_id"`

	// ReadyReplicas Observed ready replica count. Nullable until first status update.
	ReadyReplicas *int `json:"ready_replicas,omitempty"`

	// Replicas Desired replica count. Nullable; DaemonSet has no scalar desired count.
	Replicas *int `json:"replicas,omitempty"`

	// Spec Kind-specific fields the collector chooses to persist (e.g. strategy
	// for Deployment, service_name for StatefulSet). Open-ended; stored
	// as JSONB.
	Spec *map[string]interface{} `json:"spec,omitempty"`
}

// WorkloadKind Kubernetes workload controller kind. Casing matches the `kind` field
// Kubernetes itself emits. Additional kinds (Job, CronJob, ReplicaSet,
// ReplicationController) may be introduced as new enum values without a
// schema migration (see ADR-0003).
type WorkloadKind string

// WorkloadList Paged list of workloads.
type WorkloadList struct {
	Items []Workload `json:"items"`

	// NextCursor Opaque cursor to pass as `?cursor=` to fetch the next page.
	// Absent or null when no more pages remain.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// WorkloadMutable Fields on a Workload that clients may set and later update.
type WorkloadMutable struct {
	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`

	// ReadyReplicas Observed ready replica count. Nullable until first status update.
	ReadyReplicas *int `json:"ready_replicas,omitempty"`

	// Replicas Desired replica count. Nullable; DaemonSet has no scalar desired count.
	Replicas *int `json:"replicas,omitempty"`

	// Spec Kind-specific fields the collector chooses to persist (e.g. strategy
	// for Deployment, service_name for StatefulSet). Open-ended; stored
	// as JSONB.
	Spec *map[string]interface{} `json:"spec,omitempty"`
}

// WorkloadUpdate Fields on a Workload that clients may set and later update.
type WorkloadUpdate = WorkloadMutable

// ClusterId defines model for ClusterId.
type ClusterId = openapi_types.UUID

// Cursor defines model for Cursor.
type Cursor = string

// Limit defines model for Limit.
type Limit = int

// NamespaceClusterIdFilter defines model for NamespaceClusterIdFilter.
type NamespaceClusterIdFilter = openapi_types.UUID

// NamespaceId defines model for NamespaceId.
type NamespaceId = openapi_types.UUID

// NodeClusterIdFilter defines model for NodeClusterIdFilter.
type NodeClusterIdFilter = openapi_types.UUID

// NodeId defines model for NodeId.
type NodeId = openapi_types.UUID

// PodId defines model for PodId.
type PodId = openapi_types.UUID

// PodNamespaceIdFilter defines model for PodNamespaceIdFilter.
type PodNamespaceIdFilter = openapi_types.UUID

// WorkloadId defines model for WorkloadId.
type WorkloadId = openapi_types.UUID

// WorkloadKindFilter Kubernetes workload controller kind. Casing matches the `kind` field
// Kubernetes itself emits. Additional kinds (Job, CronJob, ReplicaSet,
// ReplicationController) may be introduced as new enum values without a
// schema migration (see ADR-0003).
type WorkloadKindFilter = WorkloadKind

// WorkloadNamespaceIdFilter defines model for WorkloadNamespaceIdFilter.
type WorkloadNamespaceIdFilter = openapi_types.UUID

// BadRequest RFC 7807 problem details.
type BadRequest = Problem

// Conflict RFC 7807 problem details.
type Conflict = Problem

// Forbidden RFC 7807 problem details.
type Forbidden = Problem

// NotFound RFC 7807 problem details.
type NotFound = Problem

// Unauthorized RFC 7807 problem details.
type Unauthorized = Problem

// ListClustersParams defines parameters for ListClusters.
type ListClustersParams struct {
	// Limit Maximum number of items to return. Server clamps to [1, 200].
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque cursor returned from a previous list response.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ListNamespacesParams defines parameters for ListNamespaces.
type ListNamespacesParams struct {
	// Limit Maximum number of items to return. Server clamps to [1, 200].
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque cursor returned from a previous list response.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// ClusterId Return only namespaces belonging to this cluster.
	ClusterId *NamespaceClusterIdFilter `form:"cluster_id,omitempty" json:"cluster_id,omitempty"`
}

// ListNodesParams defines parameters for ListNodes.
type ListNodesParams struct {
	// Limit Maximum number of items to return. Server clamps to [1, 200].
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque cursor returned from a previous list response.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// ClusterId Return only nodes belonging to this cluster.
	ClusterId *NodeClusterIdFilter `form:"cluster_id,omitempty" json:"cluster_id,omitempty"`
}

// ListPodsParams defines parameters for ListPods.
type ListPodsParams struct {
	// Limit Maximum number of items to return. Server clamps to [1, 200].
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque cursor returned from a previous list response.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// NamespaceId Return only pods belonging to this namespace.
	NamespaceId *PodNamespaceIdFilter `form:"namespace_id,omitempty" json:"namespace_id,omitempty"`
}

// ListWorkloadsParams defines parameters for ListWorkloads.
type ListWorkloadsParams struct {
	// Limit Maximum number of items to return. Server clamps to [1, 200].
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque cursor returned from a previous list response.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// NamespaceId Return only workloads belonging to this namespace.
	NamespaceId *WorkloadNamespaceIdFilter `form:"namespace_id,omitempty" json:"namespace_id,omitempty"`

	// Kind Return only workloads of this kind.
	Kind *WorkloadKindFilter `form:"kind,omitempty" json:"kind,omitempty"`
}

// CreateClusterJSONRequestBody defines body for CreateCluster for application/json ContentType.
type CreateClusterJSONRequestBody = ClusterCreate

// UpdateClusterApplicationMergePatchPlusJSONRequestBody defines body for UpdateCluster for application/merge-patch+json ContentType.
type UpdateClusterApplicationMergePatchPlusJSONRequestBody = ClusterUpdate

// CreateNamespaceJSONRequestBody defines body for CreateNamespace for application/json ContentType.
type CreateNamespaceJSONRequestBody = NamespaceCreate

// UpdateNamespaceApplicationMergePatchPlusJSONRequestBody defines body for UpdateNamespace for application/merge-patch+json ContentType.
type UpdateNamespaceApplicationMergePatchPlusJSONRequestBody = NamespaceUpdate

// CreateNodeJSONRequestBody defines body for CreateNode for application/json ContentType.
type CreateNodeJSONRequestBody = NodeCreate

// UpdateNodeApplicationMergePatchPlusJSONRequestBody defines body for UpdateNode for application/merge-patch+json ContentType.
type UpdateNodeApplicationMergePatchPlusJSONRequestBody = NodeUpdate

// CreatePodJSONRequestBody defines body for CreatePod for application/json ContentType.
type CreatePodJSONRequestBody = PodCreate

// UpdatePodApplicationMergePatchPlusJSONRequestBody defines body for UpdatePod for application/merge-patch+json ContentType.
type UpdatePodApplicationMergePatchPlusJSONRequestBody = PodUpdate

// CreateWorkloadJSONRequestBody defines body for CreateWorkload for application/json ContentType.
type CreateWorkloadJSONRequestBody = WorkloadCreate

// UpdateWorkloadApplicationMergePatchPlusJSONRequestBody defines body for UpdateWorkload for application/merge-patch+json ContentType.
type UpdateWorkloadApplicationMergePatchPlusJSONRequestBody = WorkloadUpdate

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Liveness probe
	// (GET /healthz)
	GetHealthz(w http.ResponseWriter, r *http.Request)
	// Readiness probe
	// (GET /readyz)
	GetReadyz(w http.ResponseWriter, r *http.Request)
	// List clusters
	// (GET /v1/clusters)
	ListClusters(w http.ResponseWriter, r *http.Request, params ListClustersParams)
	// Register a cluster
	// (POST /v1/clusters)
	CreateCluster(w http.ResponseWriter, r *http.Request)
	// Delete a cluster
	// (DELETE /v1/clusters/{id})
	DeleteCluster(w http.ResponseWriter, r *http.Request, id ClusterId)
	// Get a cluster
	// (GET /v1/clusters/{id})
	GetCluster(w http.ResponseWriter, r *http.Request, id ClusterId)
	// Update mutable fields of a cluster
	// (PATCH /v1/clusters/{id})
	UpdateCluster(w http.ResponseWriter, r *http.Request, id ClusterId)
	// List namespaces
	// (GET /v1/namespaces)
	ListNamespaces(w http.ResponseWriter, r *http.Request, params ListNamespacesParams)
	// Register a namespace
	// (POST /v1/namespaces)
	CreateNamespace(w http.ResponseWriter, r *http.Request)
	// Delete a namespace
	// (DELETE /v1/namespaces/{id})
	DeleteNamespace(w http.ResponseWriter, r *http.Request, id NamespaceId)
	// Get a namespace
	// (GET /v1/namespaces/{id})
	GetNamespace(w http.ResponseWriter, r *http.Request, id NamespaceId)
	// Update mutable fields of a namespace
	// (PATCH /v1/namespaces/{id})
	UpdateNamespace(w http.ResponseWriter, r *http.Request, id NamespaceId)
	// List nodes
	// (GET /v1/nodes)
	ListNodes(w http.ResponseWriter, r *http.Request, params ListNodesParams)
	// Register a node
	// (POST /v1/nodes)
	CreateNode(w http.ResponseWriter, r *http.Request)
	// Delete a node
	// (DELETE /v1/nodes/{id})
	DeleteNode(w http.ResponseWriter, r *http.Request, id NodeId)
	// Get a node
	// (GET /v1/nodes/{id})
	GetNode(w http.ResponseWriter, r *http.Request, id NodeId)
	// Update mutable fields of a node
	// (PATCH /v1/nodes/{id})
	UpdateNode(w http.ResponseWriter, r *http.Request, id NodeId)
	// List pods
	// (GET /v1/pods)
	ListPods(w http.ResponseWriter, r *http.Request, params ListPodsParams)
	// Register a pod
	// (POST /v1/pods)
	CreatePod(w http.ResponseWriter, r *http.Request)
	// Delete a pod
	// (DELETE /v1/pods/{id})
	DeletePod(w http.ResponseWriter, r *http.Request, id PodId)
	// Get a pod
	// (GET /v1/pods/{id})
	GetPod(w http.ResponseWriter, r *http.Request, id PodId)
	// Update mutable fields of a pod
	// (PATCH /v1/pods/{id})
	UpdatePod(w http.ResponseWriter, r *http.Request, id PodId)
	// List workloads
	// (GET /v1/workloads)
	ListWorkloads(w http.ResponseWriter, r *http.Request, params ListWorkloadsParams)
	// Register a workload
	// (POST /v1/workloads)
	CreateWorkload(w http.ResponseWriter, r *http.Request)
	// Delete a workload
	// (DELETE /v1/workloads/{id})
	DeleteWorkload(w http.ResponseWriter, r *http.Request, id WorkloadId)
	// Get a workload
	// (GET /v1/workloads/{id})
	GetWorkload(w http.ResponseWriter, r *http.Request, id WorkloadId)
	// Update mutable fields of a workload
	// (PATCH /v1/workloads/{id})
	UpdateWorkload(w http.ResponseWriter, r *http.Request, id WorkloadId)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReadyz operation middleware
func (siw *ServerInterfaceWrapper) GetReadyz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReadyz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListClusters operation middleware
func (siw *ServerInterfaceWrapper) ListClusters(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"read"})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListClustersParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListClusters(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateCluster operation middleware
func (siw *ServerInterfaceWrapper) CreateCluster(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"write"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCluster(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteCluster operation middleware
func (siw *ServerInterfaceWrapper) DeleteCluster(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ClusterId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"delete"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteCluster(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCluster operation middleware
func (siw *ServerInterfaceWrapper) GetCluster(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ClusterId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"read"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCluster(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateCluster operation middleware
func (siw *ServerInterfaceWrapper) UpdateCluster(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ClusterId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"write"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateCluster(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListNamespaces operation middleware
func (siw *ServerInterfaceWrapper) ListNamespaces(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"read"})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListNamespacesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		return
	}

	// ------------- Optional query parameter "cluster_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cluster_id", r.URL.Query(), &params.ClusterId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cluster_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListNamespaces(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateNamespace operation middleware
func (siw *ServerInterfaceWrapper) CreateNamespace(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"write"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateNamespace(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteNamespace operation middleware
func (siw *ServerInterfaceWrapper) DeleteNamespace(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id NamespaceId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"delete"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteNamespace(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetNamespace operation middleware
func (siw *ServerInterfaceWrapper) GetNamespace(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id NamespaceId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"read"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetNamespace(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateNamespace operation middleware
func (siw *ServerInterfaceWrapper) UpdateNamespace(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id NamespaceId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"write"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateNamespace(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListNodes operation middleware
func (siw *ServerInterfaceWrapper) ListNodes(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"read"})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListNodesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		return
	}

	// ------------- Optional query parameter "cluster_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cluster_id", r.URL.Query(), &params.ClusterId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cluster_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListNodes(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateNode operation middleware
func (siw *ServerInterfaceWrapper) CreateNode(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"write"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateNode(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteNode operation middleware
func (siw *ServerInterfaceWrapper) DeleteNode(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id NodeId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"delete"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteNode(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetNode operation middleware
func (siw *ServerInterfaceWrapper) GetNode(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id NodeId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"read"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetNode(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateNode operation middleware
func (siw *ServerInterfaceWrapper) UpdateNode(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id NodeId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"write"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateNode(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListPods operation middleware
func (siw *ServerInterfaceWrapper) ListPods(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"read"})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListPodsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		return
	}

	// ------------- Optional query parameter "namespace_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "namespace_id", r.URL.Query(), &params.NamespaceId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPods(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreatePod operation middleware
func (siw *ServerInterfaceWrapper) CreatePod(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"write"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreatePod(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeletePod operation middleware
func (siw *ServerInterfaceWrapper) DeletePod(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id PodId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"delete"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeletePod(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPod operation middleware
func (siw *ServerInterfaceWrapper) GetPod(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id PodId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"read"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPod(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdatePod operation middleware
func (siw *ServerInterfaceWrapper) UpdatePod(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id PodId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"write"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdatePod(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListWorkloads operation middleware
func (siw *ServerInterfaceWrapper) ListWorkloads(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"read"})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListWorkloadsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		return
	}

	// ------------- Optional query parameter "namespace_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "namespace_id", r.URL.Query(), &params.NamespaceId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace_id", Err: err})
		return
	}

	// ------------- Optional query parameter "kind" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "kind", r.URL.Query(), &params.Kind, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "kind", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListWorkloads(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateWorkload operation middleware
func (siw *ServerInterfaceWrapper) CreateWorkload(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"write"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateWorkload(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteWorkload operation middleware
func (siw *ServerInterfaceWrapper) DeleteWorkload(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id WorkloadId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"delete"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteWorkload(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWorkload operation middleware
func (siw *ServerInterfaceWrapper) GetWorkload(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id WorkloadId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"read"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWorkload(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateWorkload operation middleware
func (siw *ServerInterfaceWrapper) UpdateWorkload(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id WorkloadId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"write"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateWorkload(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/healthz", wrapper.GetHealthz)
	m.HandleFunc("GET "+options.BaseURL+"/readyz", wrapper.GetReadyz)
	m.HandleFunc("GET "+options.BaseURL+"/v1/clusters", wrapper.ListClusters)
	m.HandleFunc("POST "+options.BaseURL+"/v1/clusters", wrapper.CreateCluster)
	m.HandleFunc("DELETE "+options.BaseURL+"/v1/clusters/{id}", wrapper.DeleteCluster)
	m.HandleFunc("GET "+options.BaseURL+"/v1/clusters/{id}", wrapper.GetCluster)
	m.HandleFunc("PATCH "+options.BaseURL+"/v1/clusters/{id}", wrapper.UpdateCluster)
	m.HandleFunc("GET "+options.BaseURL+"/v1/namespaces", wrapper.ListNamespaces)
	m.HandleFunc("POST "+options.BaseURL+"/v1/namespaces", wrapper.CreateNamespace)
	m.HandleFunc("DELETE "+options.BaseURL+"/v1/namespaces/{id}", wrapper.DeleteNamespace)
	m.HandleFunc("GET "+options.BaseURL+"/v1/namespaces/{id}", wrapper.GetNamespace)
	m.HandleFunc("PATCH "+options.BaseURL+"/v1/namespaces/{id}", wrapper.UpdateNamespace)
	m.HandleFunc("GET "+options.BaseURL+"/v1/nodes", wrapper.ListNodes)
	m.HandleFunc("POST "+options.BaseURL+"/v1/nodes", wrapper.CreateNode)
	m.HandleFunc("DELETE "+options.BaseURL+"/v1/nodes/{id}", wrapper.DeleteNode)
	m.HandleFunc("GET "+options.BaseURL+"/v1/nodes/{id}", wrapper.GetNode)
	m.HandleFunc("PATCH "+options.BaseURL+"/v1/nodes/{id}", wrapper.UpdateNode)
	m.HandleFunc("GET "+options.BaseURL+"/v1/pods", wrapper.ListPods)
	m.HandleFunc("POST "+options.BaseURL+"/v1/pods", wrapper.CreatePod)
	m.HandleFunc("DELETE "+options.BaseURL+"/v1/pods/{id}", wrapper.DeletePod)
	m.HandleFunc("GET "+options.BaseURL+"/v1/pods/{id}", wrapper.GetPod)
	m.HandleFunc("PATCH "+options.BaseURL+"/v1/pods/{id}", wrapper.UpdatePod)
	m.HandleFunc("GET "+options.BaseURL+"/v1/workloads", wrapper.ListWorkloads)
	m.HandleFunc("POST "+options.BaseURL+"/v1/workloads", wrapper.CreateWorkload)
	m.HandleFunc("DELETE "+options.BaseURL+"/v1/workloads/{id}", wrapper.DeleteWorkload)
	m.HandleFunc("GET "+options.BaseURL+"/v1/workloads/{id}", wrapper.GetWorkload)
	m.HandleFunc("PATCH "+options.BaseURL+"/v1/workloads/{id}", wrapper.UpdateWorkload)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xd/XLbOJJ/lS7eVp09S8mK42QnTl1teZzNjncyjsqe3P4R5WKIaElYkwADgHY0KVfd",
	"Q9wT3pNcNcAvSZQo+UOXcfKPLZEg0OjPX4No6EsQqSRVEqU1weGXIGWaJWhRu2/HcWYs6hNOXziaSIvU",
	"CiWDw+Ac9RXqDjNGjCVyiHxTEBylFSOBuhuEgaCmKbOTIAwkSzA4DAQPwkDjp0xo5MGh1RmGgYkmmDAa",
	"ZaR0wmxwGGSZa2mnKT1lrBZyHNzchMFxpo3SixS9TdmnDCFyt0GjzTQRNtIqAQapxiuhMgOxMBY0mlRJ",
	"gyWNnzLU04pI30lQJyxhn9+gHNtJcPjsyX4TYW9EIuwiXb+yzyLJEpBZMkQNagTCYmLAqpzILnhmQhSz",
	"JHU33j8JYb/X+7CMvtgNVSeP44hlsQ0On/VCopWGDA73e/RNSP/tSUm1kBbHqB3ZpyxBk7IIS2m/FrHF",
	"Bg6fOXJByXgKsnjKwBBjJcdCjolyOxGmUIal3PW3PzoBbyL6ktR1NLKkcAs6ear4huxTfLucU3w9pim+",
	"DX71FV+HmlTx7RBTU6x1pJcq3iS8UuOWia9ssLkA/6n0ZazYWmy7zttugXcFWb8IuRbnCtIM+UHHtEsh",
	"+TJ+0b0ZPv1J4yg4DP5tr4pae/6u2auTMkPbhsKtSNymhG9IDj4oudD7E+Nn+ClD4yJKpKRF6T6yNI1F",
	"xIjwvVSrYYzJn/9laBZf1mRU3z/lB52PVTERihy0H7wbUMRVchSLaKuUFGPCtbATCuoapQVjmUXYwe64",
	"GwLP/PjoxLLrSH2t9FBwjnKbtP6mLlGCMHDFYsFhmFmIWXRpwE4QTKRShMLGYDh1V1WK2lHjqD5V9rXK",
	"JN8m0WdoVKYjBKksjGh0R8o7yTI7UVr8jlsl51dhDFma0iBkzkdkGjVY4m7XWXTeTw2aOrri+O0oOHy/",
	"euz8gV8zy4YxBjfhlyDVJAYrvMVFGplF/pHZGXvlzGLHigSdp2T8rYynhaecM+KQ/GmDrbc+FrPpJlN5",
	"45rffJjn4VF8zaYGLoQcaWasziKbafwYq7GIWHwBI6UhZwNhTlsoo3Hxo7tA6U3h1mbQ7/MDBymLr/sh",
	"xRSLmij4r/es83uv8+JD/r/z4UsvfL5/U1z+U9Aw+yzld2T8TT2IvfdRzVFesDasS3dmxA9lZ2r4L4xs",
	"E1vhl2yIWqLFEqCBxrGgD8hBSMfF419f/eTdpW9y7Ea8RwUtZDEX/F1zMHE27sTiso7eQsikoJyIRVoZ",
	"U1E5kCdJ4scBNqLpOPaQOxrIIHxAac9Jyk1pDRH02dQBGpczecYDA4nXFWCuGP9GmIY0rM/GyH32p0bF",
	"Y4aUfpbLLjmb+bCG0Gj0fA5Mazal7xI/24/RWsmqVZAyY4AZuPirv/YfF3R1hDaaOLlRb5CyMXYH8mho",
	"KBgqDTKLY7ieoASpIFEaXRMDGhMmcmFSG6dR69mOm/WiSEruFvq5MKXXAmPCdRJY4WXATpiFKBbEM0jY",
	"FAxaYJJDzOi2t8NFGbBUfETJUyVkgyRr1njUP8m9F7w7ewM7Qnr3IZRk8S51XPliLZqcDxcmjdn0Y7Nx",
	"/ZwlTHZGWqDk8RRiNsQ4hJFG7FDH3Vlb2X/2vGEElFdCK5lg01xeF11BrRlYNi5BDl6FBHsIhoaQasV3",
	"u4sWujDoZcmjj1eojfBReg5i5UKqMTFvCxpTpa2HKzV2O5pgEDzp7r/oPhsE86Q83W8MbkOMvVg5F140",
	"/Rlxt7Jwzh/robCa6SlkBnXHZIRLkINvD5c43bticYZeXCansT5kjWWVfqdaXQnelB28kxx1PKXOa8zg",
	"ggYcZtSIbHGijKUmRT/dgXybouyg5MhfQqSSRElwlJlDGF9iCHhpQmD0R6UozUSMbAia7pD8GE9CUDLV",
	"SP/txHW5huzJQ3p5r255s9zI3znDvH3sWnDgv6IeYydl5M6Gik+7QOEciiA0cr7jJVyQGV4QlBZFgCI2",
	"JsKSMvpWwDRCjCMLmYwmTI6RE19uwuBnZDHNdT5wUtaQuU8os4S8nLqsubiKc0tN5adMxLy0Dpe6IuhM",
	"ShI402NlXA672rXmZDT51jcFAJzT9NPz8xOImLZqrFk6IQ80dW4VgRnypT5FNWAVITqEo1dnnV6vt++w",
	"np3gQFIO3bGq459MWJo6miX3c8h9JcIQJyK/aMTnorniGHutK1iHkTJTYzEJwmCYGSHRmCCskoMrQl2M",
	"J0KSfbjuXa7cBEkXb6STqXF3msRTJvLrK2b5yArcX62ptefp4TeSJpR8u0ui8HQGOj5phI477zv5px+K",
	"S7t/3WKaMLOi+kA5Q7USvSJrqJbhN8wbNlbxeVzsVlaq9zddWJYcvHQUFy2TzNiBZDExfQr42SFr75s8",
	"4/LXGwYOegfeh7QaVzMKa2QlfYKdV6fnHRfmwdhpjLtdeOdTntS9T/G5wSbpzn3q7Jy+LaranTKfihUZ",
	"4RNgM7lQqRXrZEPVy5y75kOVi/4GMqIFy1uZE5Wtb5sVPXyq8oeB6hNm1vUTri3pUcxI2YcuhvEylTmK",
	"CLIMghAGwW+oEyEZoXjKber4nVSPRQ7Dk3CAySlUPPKDmLrPF9JqxTMyqXkf83R/LShe6sumYHwxINwa",
	"jlcu68IpaI7PmcaBrBA6rAvQTxXfZB6Kf4dtrbCtQMw5blP8LpBt/9nTNZb7yvjXfcygTfHVeE3xzaHa",
	"Bhr9h0ZpxLsKoJlsyBWF33sCafespQ8M04gXjQhN8fXAmeL3gMvI834LkKxmYavRGInltsvTOpoIi87/",
	"Niyr9t9BvUUXViwDsoQ/PwiB6YT+pWn0/CDGEMzTF73P6wCHbSxgX2ZDjNEuX0j+xTeAsbDlGhkzbYvI",
	"V49yFVmZjyJh4wZROI17ew7udjFMwYx3w0zaDPb3u72D7lN489v5Il+aZnWzxAY2xoz1yPS1wMW+4uvP",
	"oK/4t/Buv7bO6hFfX/F7BHxP7gr4ZjZArQPMH+7tf20f1gNhxFTxVRCxr/imCHGlFrfiLqJnTdhV7WS7",
	"A/C6d21pBL31jbxtsLdsO5CEfOE+gW/D3oV5FbsTUiTpFUCxttHQK9I6SDFV/M5AkXzuN4ATa3a2Eib2",
	"Fb8tSvyjIBbKL5agx1PyJfnbTukBM/pN2QZIYXgWIwcluw1uYmEy7Yt21HPzct0h9FFytwXizL91DeE8",
	"iyJEjjwcyNdMxMhD0qJ38lKqa1lH3Wst3q2HtlPFP4q0wRAVh5M+9arRGNg56V8dEDUn/avnu104qe9L",
	"eem2XLo9jhR4aLJMDuRJH2JhUbN4gZSDZ2sBv77im+K+ery500v7whPeD/DL94ku7tN+fQx/+bH3F8j3",
	"nwJHy0Tc4PX8Dfq0uCFHa6XNErvvxHiFcSEdymR889B7phx+0WyCsPKos2O76TUOnaAxeXKw2nP5LqoH",
	"mnzYvI8W0lgm/dvxtm1P1ZaIslbo2YsX9VqhXm+xWigMrLAxNk7NX6gVIgVsqDJ7OIyZvGzdiDU3fXe3",
	"GC1ctXOi2OS/vsoXT3yV2YKreNio0OHhM4xivO9pRluakderPFC2UZb1REpareJ49TbkQmybpiDt9lEo",
	"6Wb9eXVdmGJx2xUCARd0z72FU3o52M/jRGtCVLJsvaxoIHdKiYaOoN3VNHzPjtbMjuqWcackqZRoc6Y0",
	"o2xraUbNmFwpGhwzV4iSEOxBv2n+gu5ceNgykPW3vNZgPAJMhDVdOKowJT1gYOcfahjCsVbSfThD51nP",
	"0YYDmX+h9sclCbsuvxhi9frYwUOaOMosyZeNXU2UyiywgfRWBokY+712sGOqbYBPd2f37r3CNFZTtxM5",
	"DM4tszjK4nOkb68YJkrS56addwVb18lCy/q5u6aiZWj/BvLReae7MiktXeYjz0ydc/qovaE0APa3xWYO",
	"78XyhhCpTNounOaigUxaEcNIaOMLCDNT40wJeBvh7vKxX6Fx9XxLBn0JpUHBhCxYgYlYzDTw/EH/QCsF",
	"JsVouaS80s05OSF5hx4TIxEVqZZz7ORiIqs0RBOlDLqTBlLUhgzXv4hwO3ZxPB1QvgqVuwgd3hORXyhw",
	"qLDmPnZnX3EZqzTygWQG/nH+9vQnbylz0r1ZYQSbJrELiOV+Mtkw9/shmdRAVjktbJzSkiAxyrSw03Mi",
	"Oq/xdQWOR5nfs+7LHV8XUdaVPQYLltY/8QWRIIzJkIPKbEeNOkMmHT6XLl5cHOU1nC4kHIIfCAZZr/c0",
	"co+7j3jRHciBPI9UigbGmkmbL5b4MQ4HEqADF2ReFwDwv//9P97Lk4sZo62qWE3e8loLixe+ZY4jqK03",
	"N9gRCfkFU/TIrNdLRqHv340Hf0j97eb9cYyROqT+NCbqinCJr1sthnRbzfMhWRwXy1VsqK7wJbX2LoJU",
	"dpTZTCO4Jzqu1rsoMjLEB1fGayBiWrtaDxf58+59Fa+jPxI2noJhVpjR1K0lzZb4DuSQLtdKfJ3+O2Ul",
	"ffdyrixiYm3qK2KFHKmGNY+/nf/manRoCj/8cKTHyvzwQwjMQX13tYZIamVEBlicHwgg7MRXA/iKgnOM",
	"TrPkOFYZh53z0+Nd+JSxmPyFxxAjzRKkOO7047eJMOV73Z1e90m3twvCAINrFl8Sp8wlyUlJiNQVksvP",
	"NeeNuEKJFHuld9KuWsAt3pTyy0tHLkrBwvHZu1dOL7OhwU8ZReN8dEI+cQyMc/f+Pqz2VIZlUAyhr7gz",
	"WV8zM4PXUFphpzk6S1iauuVLV92PsKTawjgm/M2tAsFIxbG6hnIdaudiWVX0RY69TJYkTE9n0GcnQmm1",
	"iLwE56UEi0KqBFKuilDUHSvjuzjqnwS18pXACcm9jk5RslQEh8FTd8mlJBPnffYmrlzmd/o8RgfrSpU9",
	"4cFh8He0P+dN5g4n2O/1VtSGb1YTnhftNJSEn/uQ41QtFlfYnfGjweH7D3XulrrmtIvYxMaGQJefZvCB",
	"Ht5zSKE+5dkh/xO1GJGH4upaGquRJcAxpcAmI7q+w5llQ2Zw17l6jSyaFKuBC9w784P9fzPPoyOr/JoN",
	"WM1GIxG5dOlZ7+k2i/xrREllPWGrpXo26zSWifXqyV5R0btUnSl3OS4ahTMnXS3BF1WTPX+2003Y2jA/",
	"nYogyINJvV7n3MDlZZXON2Fw4Klo6rykdq929Ih75En7IzOnRriHnrY/VJ3VMacBs8jovcsDgg83c+Zu",
	"yu2QpqYW5aUP7m2NaVAEvyBWVG77DA2N/Unx6X2LKF97u5lNBPN10jn9eHLfgzceq5JvC83XJMltTZDx",
	"3G7eKD9eQwns2Un5IhCv42nRQf3AqqbDbhrX+m++Yk2kJ160P1EeidOiug4Qz+vuWbWkFZVa2KDAc55t",
	"74vgN140hIoXFfuVu15X7BkFO1heAu575N2tsvmg/YnyYJwWNuccmeOz50cbl8Ol6GcpJ3vbNNXyFecf",
	"VDZN3vvvaNvFslmErs6qpKFcqt9wFmNtHcBgwqQVkTkskndV5PJaJc7VDRWfOpxXz+YbatQb3wzMqpNf",
	"09g06CQVvX++lWLlSylrBaCtaLUniM/shP+aY8E9GkJjLPD8mFuJolC7XmyoKjdX4t7TqtmDI9/2lktP",
	"HH1Q1DxbEduKm+s1sY8POcu6QhTqVbvYhp6rOt+Hwc/z1fBbRtC1MuZFPakKee8NRc+cK/locPRGvnPL",
	"wFvWFLhR/xcc7Jrwe9Yy2gB4pUuPHIK38ns5DF/B0d62Lf7xgvE1BLQZcKgf1v3QkHx54dEtQPrmse32",
	"MH2+yH/LQH2l1hdQfXaHzXew3gjW144nirdhddfia4DpDYfaPyxCLyqi28G5r4l+hLg8F36pQu57KxpX",
	"/MGAeHXMwbYxuCtZbwjGit8n8lb8O+jeGuj2ejqv3HXXuC7KLjS+FWCTtjx2bN3M1hWIupF7ve2Y7iOG",
	"0MvksCFw9r/V8sfCzJtEoDvA5epog20j5SUqXYJkF0e+4+Ol+Hil608VXw2K+9TgK8DEjb8V9KCguKj9",
	"bsXEvvr78UHi1Iu+0Bz3tQ0Q9xV/IDxcnemwZTjsCvMbdEDx+wPDqeLfsfCWsHDqVHROq2vucE0gXGh6",
	"Gw4mPXnkMLiRo8tBcCPnetuw18eLgJeIYLOw7X8ccBu7OJYdWnALALxJxLk9/q1OeNgy/F2izQX6dYHj",
	"O/hdBn5X+fqyXHIl/v1n2eorAMHLf1hxg4drvxj5oPh5pnS1FUTXilcfH5K+rilRoYzVtTZMXZbjPgyw",
	"njuuYMvouqo1XtSQstz23nB2wfTvYHtLYPu60t0mxZ93xWti7xmLaAPgpRY9chTewurleHw5N3vbNfPH",
	"C89bZbMZtKj9JvVW0fpMYfbdYPvGQe322H2uun3LAH6V5hcovgpL36H8MijfFklWjuaHcSdneQOblQMh",
	"iRg4XmGs0vyUlkzHeY344d5eTA0mytjDH3s/9pzR5UQsdLWq8hp2MicEJFMkybuTpvNfMM/rKgnJLz08",
	"p9iHvvT4qbK3csf6yv7c2wDYIUaihr3iTJ5OGjOJkLBoQuTvugppIevn6Fc/vO5eKKwepdyOs7KjatPO",
	"yt4oi3OHDrjTBqxKRAS1o9PqBxUJa2oDuPRvZdcNZxMZ2KmfxlE7fCOsThrZ7Q7kERghx3F52odQElIV",
	"TxOl04mIQMn6iUYzx229hPrRQfn5Np7mSsVvPtz8XwAAAP//zHC20jSGAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
