//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for HealthStatus.
const (
	Ok HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for Layer.
const (
	Administration         Layer = "administration"
	Applicative            Layer = "applicative"
	Business               Layer = "business"
	Ecosystem              Layer = "ecosystem"
	InfrastructureLogical  Layer = "infrastructure_logical"
	InfrastructurePhysical Layer = "infrastructure_physical"
)

// Valid indicates whether the value is a known member of the Layer enum.
func (e Layer) Valid() bool {
	switch e {
	case Administration:
		return true
	case Applicative:
		return true
	case Business:
		return true
	case Ecosystem:
		return true
	case InfrastructureLogical:
		return true
	case InfrastructurePhysical:
		return true
	default:
		return false
	}
}

// Defines values for ServiceType.
const (
	ClusterIP    ServiceType = "ClusterIP"
	ExternalName ServiceType = "ExternalName"
	LoadBalancer ServiceType = "LoadBalancer"
	NodePort     ServiceType = "NodePort"
)

// Valid indicates whether the value is a known member of the ServiceType enum.
func (e ServiceType) Valid() bool {
	switch e {
	case ClusterIP:
		return true
	case ExternalName:
		return true
	case LoadBalancer:
		return true
	case NodePort:
		return true
	default:
		return false
	}
}

// Defines values for WorkloadKind.
const (
	DaemonSet   WorkloadKind = "DaemonSet"
	Deployment  WorkloadKind = "Deployment"
	StatefulSet WorkloadKind = "StatefulSet"
)

// Valid indicates whether the value is a known member of the WorkloadKind enum.
func (e WorkloadKind) Valid() bool {
	switch e {
	case DaemonSet:
		return true
	case Deployment:
		return true
	case StatefulSet:
		return true
	default:
		return false
	}
}

// Cluster defines model for Cluster.
type Cluster struct {
	// ApiEndpoint Kubernetes API server URL (informational).
	ApiEndpoint *string    `json:"api_endpoint,omitempty"`
	CreatedAt   *time.Time `json:"created_at,omitempty"`

	// DisplayName Human-friendly label, free-form.
	DisplayName *string `json:"display_name,omitempty"`

	// Environment Free-form environment tag (e.g., dev, staging, prod).
	Environment *string             `json:"environment,omitempty"`
	Id          *openapi_types.UUID `json:"id,omitempty"`

	// KubernetesVersion Cluster API server version reported by Kubernetes (e.g. "1.29.5").
	KubernetesVersion *string `json:"kubernetes_version,omitempty"`

	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`

	// Layer Always `infrastructure_logical` for Cluster. Set by the server.
	Layer *Layer `json:"layer,omitempty"`
	Name  string `json:"name"`

	// Provider Underlying Kubernetes distribution or hosting provider.
	// Open-ended; common values: gke, eks, aks, openshift, rke, kubeadm, onprem, other.
	Provider  *string    `json:"provider,omitempty"`
	Region    *string    `json:"region,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// ClusterCreate defines model for ClusterCreate.
type ClusterCreate struct {
	// ApiEndpoint Kubernetes API server URL (informational).
	ApiEndpoint *string `json:"api_endpoint,omitempty"`

	// DisplayName Human-friendly label, free-form.
	DisplayName *string `json:"display_name,omitempty"`

	// Environment Free-form environment tag (e.g., dev, staging, prod).
	Environment *string `json:"environment,omitempty"`

	// KubernetesVersion Cluster API server version reported by Kubernetes (e.g. "1.29.5").
	KubernetesVersion *string `json:"kubernetes_version,omitempty"`

	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`

	// Name Stable slug-like identifier, unique across the CMDB.
	// Immutable after creation.
	Name string `json:"name"`

	// Provider Underlying Kubernetes distribution or hosting provider.
	// Open-ended; common values: gke, eks, aks, openshift, rke, kubeadm, onprem, other.
	Provider *string `json:"provider,omitempty"`
	Region   *string `json:"region,omitempty"`
}

// ClusterList Paged list of clusters.
type ClusterList struct {
	Items []Cluster `json:"items"`

	// NextCursor Opaque cursor to pass as `?cursor=` to fetch the next page.
	// Absent or null when no more pages remain.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// ClusterMutable Fields on a Cluster that clients may set and later update.
type ClusterMutable struct {
	// ApiEndpoint Kubernetes API server URL (informational).
	ApiEndpoint *string `json:"api_endpoint,omitempty"`

	// DisplayName Human-friendly label, free-form.
	DisplayName *string `json:"display_name,omitempty"`

	// Environment Free-form environment tag (e.g., dev, staging, prod).
	Environment *string `json:"environment,omitempty"`

	// KubernetesVersion Cluster API server version reported by Kubernetes (e.g. "1.29.5").
	KubernetesVersion *string `json:"kubernetes_version,omitempty"`

	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`

	// Provider Underlying Kubernetes distribution or hosting provider.
	// Open-ended; common values: gke, eks, aks, openshift, rke, kubeadm, onprem, other.
	Provider *string `json:"provider,omitempty"`
	Region   *string `json:"region,omitempty"`
}

// ClusterUpdate Fields on a Cluster that clients may set and later update.
type ClusterUpdate = ClusterMutable

// ContainerList Containers associated with the resource. For Pods this reflects the
// live runtime (name, image, image_id from containerStatuses, init
// flag); for Workloads it's the pod template's declared containers
// (name, image, init). Opaque in v1: each entry's shape is additive,
// so new collector-extracted fields don't require a spec bump.
type ContainerList = []map[string]interface{}

// Health defines model for Health.
type Health struct {
	Status HealthStatus `json:"status"`

	// Version Build version of the running argosd.
	Version *string `json:"version,omitempty"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// Ingress defines model for Ingress.
type Ingress struct {
	CreatedAt *time.Time          `json:"created_at,omitempty"`
	Id        *openapi_types.UUID `json:"id,omitempty"`

	// IngressClassName IngressClass name the controller binds to (e.g., "nginx", "traefik").
	IngressClassName *string `json:"ingress_class_name,omitempty"`

	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`

	// Layer Always `applicative` for Ingress. See ADR-0004.
	Layer       *Layer             `json:"layer,omitempty"`
	Name        string             `json:"name"`
	NamespaceId openapi_types.UUID `json:"namespace_id"`

	// Rules Ingress routing rules. Opaque in v1: each entry carries whatever the
	// collector chose to persist (host, path, path_type, backend service
	// name / port).
	Rules *[]map[string]interface{} `json:"rules,omitempty"`

	// Tls TLS configuration entries. Opaque in v1: each entry carries hosts
	// and the referenced Secret name.
	Tls       *[]map[string]interface{} `json:"tls,omitempty"`
	UpdatedAt *time.Time                `json:"updated_at,omitempty"`
}

// IngressCreate defines model for IngressCreate.
type IngressCreate struct {
	// IngressClassName IngressClass name the controller binds to (e.g., "nginx", "traefik").
	IngressClassName *string `json:"ingress_class_name,omitempty"`

	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`

	// Name Kubernetes ingress name (DNS-label style). Unique per namespace.
	// Immutable after creation.
	Name string `json:"name"`

	// NamespaceId Parent namespace id. Immutable after creation; the namespace
	// must already exist or the create returns 404.
	NamespaceId openapi_types.UUID `json:"namespace_id"`

	// Rules Ingress routing rules. Opaque in v1: each entry carries whatever the
	// collector chose to persist (host, path, path_type, backend service
	// name / port).
	Rules *[]map[string]interface{} `json:"rules,omitempty"`

	// Tls TLS configuration entries. Opaque in v1: each entry carries hosts
	// and the referenced Secret name.
	Tls *[]map[string]interface{} `json:"tls,omitempty"`
}

// IngressList Paged list of ingresses.
type IngressList struct {
	Items []Ingress `json:"items"`

	// NextCursor Opaque cursor to pass as `?cursor=` to fetch the next page.
	// Absent or null when no more pages remain.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// IngressMutable Fields on an Ingress that clients may set and later update.
type IngressMutable struct {
	// IngressClassName IngressClass name the controller binds to (e.g., "nginx", "traefik").
	IngressClassName *string `json:"ingress_class_name,omitempty"`

	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`

	// Rules Ingress routing rules. Opaque in v1: each entry carries whatever the
	// collector chose to persist (host, path, path_type, backend service
	// name / port).
	Rules *[]map[string]interface{} `json:"rules,omitempty"`

	// Tls TLS configuration entries. Opaque in v1: each entry carries hosts
	// and the referenced Secret name.
	Tls *[]map[string]interface{} `json:"tls,omitempty"`
}

// IngressUpdate Fields on an Ingress that clients may set and later update.
type IngressUpdate = IngressMutable

// Layer ANSSI cartography layer the asset belongs to. See ADR-0002 for the
// kind-to-layer mapping and the rationale behind the six-layer model.
type Layer string

// Namespace defines model for Namespace.
type Namespace struct {
	ClusterId openapi_types.UUID `json:"cluster_id"`
	CreatedAt *time.Time         `json:"created_at,omitempty"`

	// DisplayName Human-friendly label, free-form.
	DisplayName *string             `json:"display_name,omitempty"`
	Id          *openapi_types.UUID `json:"id,omitempty"`

	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`

	// Layer Always `infrastructure_logical` for Namespace. Set by the server.
	Layer *Layer `json:"layer,omitempty"`
	Name  string `json:"name"`

	// Phase Kubernetes namespace phase as last observed (e.g. "Active", "Terminating").
	// Open-ended to accommodate any additional phases Kubernetes introduces.
	Phase     *string    `json:"phase,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// NamespaceCreate defines model for NamespaceCreate.
type NamespaceCreate struct {
	// ClusterId Parent cluster id. Immutable after creation; the cluster must
	// already exist or the create returns 404.
	ClusterId openapi_types.UUID `json:"cluster_id"`

	// DisplayName Human-friendly label, free-form.
	DisplayName *string `json:"display_name,omitempty"`

	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`

	// Name Kubernetes namespace name (DNS-label style). Unique per cluster.
	// Immutable after creation.
	Name string `json:"name"`

	// Phase Kubernetes namespace phase as last observed (e.g. "Active", "Terminating").
	// Open-ended to accommodate any additional phases Kubernetes introduces.
	Phase *string `json:"phase,omitempty"`
}

// NamespaceList Paged list of namespaces.
type NamespaceList struct {
	Items []Namespace `json:"items"`

	// NextCursor Opaque cursor to pass as `?cursor=` to fetch the next page.
	// Absent or null when no more pages remain.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// NamespaceMutable Fields on a Namespace that clients may set and later update.
type NamespaceMutable struct {
	// DisplayName Human-friendly label, free-form.
	DisplayName *string `json:"display_name,omitempty"`

	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`

	// Phase Kubernetes namespace phase as last observed (e.g. "Active", "Terminating").
	// Open-ended to accommodate any additional phases Kubernetes introduces.
	Phase *string `json:"phase,omitempty"`
}

// NamespaceUpdate Fields on a Namespace that clients may set and later update.
type NamespaceUpdate = NamespaceMutable

// Node defines model for Node.
type Node struct {
	// Architecture CPU architecture. Open-ended; common values: amd64, arm64, ppc64le, s390x.
	Architecture *string            `json:"architecture,omitempty"`
	ClusterId    openapi_types.UUID `json:"cluster_id"`
	CreatedAt    *time.Time         `json:"created_at,omitempty"`

	// DisplayName Human-friendly label, free-form.
	DisplayName *string             `json:"display_name,omitempty"`
	Id          *openapi_types.UUID `json:"id,omitempty"`

	// KubeletVersion Kubelet git version as reported by Kubernetes (e.g. "v1.29.5").
	KubeletVersion *string `json:"kubelet_version,omitempty"`

	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`

	// Layer Always `infrastructure_physical` for Node. Set by the server.
	Layer *Layer `json:"layer,omitempty"`
	Name  string `json:"name"`

	// OsImage Node OS image string (e.g. "Ubuntu 22.04.3 LTS").
	OsImage   *string    `json:"os_image,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// NodeCreate defines model for NodeCreate.
type NodeCreate struct {
	// Architecture CPU architecture. Open-ended; common values: amd64, arm64, ppc64le, s390x.
	Architecture *string `json:"architecture,omitempty"`

	// ClusterId Parent cluster id. Immutable after creation; the cluster must
	// already exist or the create returns 404.
	ClusterId openapi_types.UUID `json:"cluster_id"`

	// DisplayName Human-friendly label, free-form.
	DisplayName *string `json:"display_name,omitempty"`

	// KubeletVersion Kubelet git version as reported by Kubernetes (e.g. "v1.29.5").
	KubeletVersion *string `json:"kubelet_version,omitempty"`

	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`

	// Name Kubernetes node name (DNS-subdomain style). Unique per cluster.
	// Immutable after creation.
	Name string `json:"name"`

	// OsImage Node OS image string (e.g. "Ubuntu 22.04.3 LTS").
	OsImage *string `json:"os_image,omitempty"`
}

// NodeList Paged list of nodes.
type NodeList struct {
	Items []Node `json:"items"`

	// NextCursor Opaque cursor to pass as `?cursor=` to fetch the next page.
	// Absent or null when no more pages remain.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// NodeMutable Fields on a Node that clients may set and later update.
type NodeMutable struct {
	// Architecture CPU architecture. Open-ended; common values: amd64, arm64, ppc64le, s390x.
	Architecture *string `json:"architecture,omitempty"`

	// DisplayName Human-friendly label, free-form.
	DisplayName *string `json:"display_name,omitempty"`

	// KubeletVersion Kubelet git version as reported by Kubernetes (e.g. "v1.29.5").
	KubeletVersion *string `json:"kubelet_version,omitempty"`

	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`

	// OsImage Node OS image string (e.g. "Ubuntu 22.04.3 LTS").
	OsImage *string `json:"os_image,omitempty"`
}

// NodeUpdate Fields on a Node that clients may set and later update.
type NodeUpdate = NodeMutable

// Pod defines model for Pod.
type Pod struct {
	// Containers Containers associated with the resource. For Pods this reflects the
	// live runtime (name, image, image_id from containerStatuses, init
	// flag); for Workloads it's the pod template's declared containers
	// (name, image, init). Opaque in v1: each entry's shape is additive,
	// so new collector-extracted fields don't require a spec bump.
	Containers *ContainerList      `json:"containers,omitempty"`
	CreatedAt  *time.Time          `json:"created_at,omitempty"`
	Id         *openapi_types.UUID `json:"id,omitempty"`

	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`

	// Layer Always `applicative` for Pod. Set by the server.
	Layer       *Layer             `json:"layer,omitempty"`
	Name        string             `json:"name"`
	NamespaceId openapi_types.UUID `json:"namespace_id"`

	// NodeName Name of the node the pod is scheduled on.
	NodeName *string `json:"node_name,omitempty"`

	// Phase Kubernetes pod phase as last observed: Pending, Running, Succeeded,
	// Failed, or Unknown. Open-ended to accommodate any additional phases.
	Phase *string `json:"phase,omitempty"`

	// PodIp Pod IP address (IPv4 or IPv6). Informational; not validated as an
	// IP literal.
	PodIp     *string    `json:"pod_ip,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`

	// WorkloadId Top-level Workload that controls this pod (Deployment /
	// StatefulSet / DaemonSet). The collector walks the K8s
	// ownerReference chain — for Deployment-owned pods this resolves
	// Pod -> ReplicaSet -> Deployment. Null for pods with no
	// controller or with an owner kind argosd doesn't model yet
	// (e.g., Job, CronJob).
	WorkloadId *openapi_types.UUID `json:"workload_id,omitempty"`
}

// PodCreate defines model for PodCreate.
type PodCreate struct {
	// Containers Containers associated with the resource. For Pods this reflects the
	// live runtime (name, image, image_id from containerStatuses, init
	// flag); for Workloads it's the pod template's declared containers
	// (name, image, init). Opaque in v1: each entry's shape is additive,
	// so new collector-extracted fields don't require a spec bump.
	Containers *ContainerList `json:"containers,omitempty"`

	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`

	// Name Kubernetes pod name (DNS-subdomain style). Unique per namespace.
	// Immutable after creation.
	Name string `json:"name"`

	// NamespaceId Parent namespace id. Immutable after creation; the namespace
	// must already exist or the create returns 404.
	NamespaceId openapi_types.UUID `json:"namespace_id"`

	// NodeName Name of the node the pod is scheduled on.
	NodeName *string `json:"node_name,omitempty"`

	// Phase Kubernetes pod phase as last observed: Pending, Running, Succeeded,
	// Failed, or Unknown. Open-ended to accommodate any additional phases.
	Phase *string `json:"phase,omitempty"`

	// PodIp Pod IP address (IPv4 or IPv6). Informational; not validated as an
	// IP literal.
	PodIp *string `json:"pod_ip,omitempty"`

	// WorkloadId Top-level Workload that controls this pod (Deployment /
	// StatefulSet / DaemonSet). The collector walks the K8s
	// ownerReference chain — for Deployment-owned pods this resolves
	// Pod -> ReplicaSet -> Deployment. Null for pods with no
	// controller or with an owner kind argosd doesn't model yet
	// (e.g., Job, CronJob).
	WorkloadId *openapi_types.UUID `json:"workload_id,omitempty"`
}

// PodList Paged list of pods.
type PodList struct {
	Items []Pod `json:"items"`

	// NextCursor Opaque cursor to pass as `?cursor=` to fetch the next page.
	// Absent or null when no more pages remain.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// PodMutable Fields on a Pod that clients may set and later update.
type PodMutable struct {
	// Containers Containers associated with the resource. For Pods this reflects the
	// live runtime (name, image, image_id from containerStatuses, init
	// flag); for Workloads it's the pod template's declared containers
	// (name, image, init). Opaque in v1: each entry's shape is additive,
	// so new collector-extracted fields don't require a spec bump.
	Containers *ContainerList `json:"containers,omitempty"`

	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`

	// NodeName Name of the node the pod is scheduled on.
	NodeName *string `json:"node_name,omitempty"`

	// Phase Kubernetes pod phase as last observed: Pending, Running, Succeeded,
	// Failed, or Unknown. Open-ended to accommodate any additional phases.
	Phase *string `json:"phase,omitempty"`

	// PodIp Pod IP address (IPv4 or IPv6). Informational; not validated as an
	// IP literal.
	PodIp *string `json:"pod_ip,omitempty"`

	// WorkloadId Top-level Workload that controls this pod (Deployment /
	// StatefulSet / DaemonSet). The collector walks the K8s
	// ownerReference chain — for Deployment-owned pods this resolves
	// Pod -> ReplicaSet -> Deployment. Null for pods with no
	// controller or with an owner kind argosd doesn't model yet
	// (e.g., Job, CronJob).
	WorkloadId *openapi_types.UUID `json:"workload_id,omitempty"`
}

// PodUpdate Fields on a Pod that clients may set and later update.
type PodUpdate = PodMutable

// Problem RFC 7807 problem details.
type Problem struct {
	Detail *string `json:"detail,omitempty"`

	// Errors Field-level validation errors, when applicable.
	Errors *[]struct {
		Field   string `json:"field"`
		Message string `json:"message"`
	} `json:"errors,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   int     `json:"status"`
	Title    string  `json:"title"`
	Type     string  `json:"type"`
}

// Service defines model for Service.
type Service struct {
	// ClusterIp Assigned ClusterIP (empty for Headless / ExternalName services).
	ClusterIp *string             `json:"cluster_ip,omitempty"`
	CreatedAt *time.Time          `json:"created_at,omitempty"`
	Id        *openapi_types.UUID `json:"id,omitempty"`

	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`

	// Layer Always `applicative` for Service. Set by the server.
	Layer       *Layer             `json:"layer,omitempty"`
	Name        string             `json:"name"`
	NamespaceId openapi_types.UUID `json:"namespace_id"`

	// Ports Service ports. Opaque in v1: each entry carries whatever the
	// collector chose to persist (name, port, target_port, protocol, node_port).
	Ports *[]map[string]interface{} `json:"ports,omitempty"`

	// Selector Pod label selector. Pods matching every key/value are selected.
	Selector *map[string]string `json:"selector,omitempty"`

	// Type Kubernetes Service type. Casing matches the enum Kubernetes itself
	// emits. Open-ended at the schema layer to accommodate future additions;
	// handler validation enforces the v1 subset.
	Type      *ServiceType `json:"type,omitempty"`
	UpdatedAt *time.Time   `json:"updated_at,omitempty"`
}

// ServiceCreate defines model for ServiceCreate.
type ServiceCreate struct {
	// ClusterIp Assigned ClusterIP (empty for Headless / ExternalName services).
	ClusterIp *string `json:"cluster_ip,omitempty"`

	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`

	// Name Kubernetes service name (DNS-label style). Unique per namespace.
	// Immutable after creation.
	Name string `json:"name"`

	// NamespaceId Parent namespace id. Immutable after creation; the namespace
	// must already exist or the create returns 404.
	NamespaceId openapi_types.UUID `json:"namespace_id"`

	// Ports Service ports. Opaque in v1: each entry carries whatever the
	// collector chose to persist (name, port, target_port, protocol, node_port).
	Ports *[]map[string]interface{} `json:"ports,omitempty"`

	// Selector Pod label selector. Pods matching every key/value are selected.
	Selector *map[string]string `json:"selector,omitempty"`

	// Type Kubernetes Service type. Casing matches the enum Kubernetes itself
	// emits. Open-ended at the schema layer to accommodate future additions;
	// handler validation enforces the v1 subset.
	Type *ServiceType `json:"type,omitempty"`
}

// ServiceList Paged list of services.
type ServiceList struct {
	Items []Service `json:"items"`

	// NextCursor Opaque cursor to pass as `?cursor=` to fetch the next page.
	// Absent or null when no more pages remain.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// ServiceMutable Fields on a Service that clients may set and later update.
type ServiceMutable struct {
	// ClusterIp Assigned ClusterIP (empty for Headless / ExternalName services).
	ClusterIp *string `json:"cluster_ip,omitempty"`

	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`

	// Ports Service ports. Opaque in v1: each entry carries whatever the
	// collector chose to persist (name, port, target_port, protocol, node_port).
	Ports *[]map[string]interface{} `json:"ports,omitempty"`

	// Selector Pod label selector. Pods matching every key/value are selected.
	Selector *map[string]string `json:"selector,omitempty"`

	// Type Kubernetes Service type. Casing matches the enum Kubernetes itself
	// emits. Open-ended at the schema layer to accommodate future additions;
	// handler validation enforces the v1 subset.
	Type *ServiceType `json:"type,omitempty"`
}

// ServiceType Kubernetes Service type. Casing matches the enum Kubernetes itself
// emits. Open-ended at the schema layer to accommodate future additions;
// handler validation enforces the v1 subset.
type ServiceType string

// ServiceUpdate Fields on a Service that clients may set and later update.
type ServiceUpdate = ServiceMutable

// Workload defines model for Workload.
type Workload struct {
	// Containers Containers associated with the resource. For Pods this reflects the
	// live runtime (name, image, image_id from containerStatuses, init
	// flag); for Workloads it's the pod template's declared containers
	// (name, image, init). Opaque in v1: each entry's shape is additive,
	// so new collector-extracted fields don't require a spec bump.
	Containers *ContainerList      `json:"containers,omitempty"`
	CreatedAt  *time.Time          `json:"created_at,omitempty"`
	Id         *openapi_types.UUID `json:"id,omitempty"`

	// Kind Kubernetes workload controller kind. Casing matches the `kind` field
	// Kubernetes itself emits. Additional kinds (Job, CronJob, ReplicaSet,
	// ReplicationController) may be introduced as new enum values without a
	// schema migration (see ADR-0003).
	Kind WorkloadKind `json:"kind"`

	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`

	// Layer Always `applicative` for Workload. Set by the server.
	Layer       *Layer             `json:"layer,omitempty"`
	Name        string             `json:"name"`
	NamespaceId openapi_types.UUID `json:"namespace_id"`

	// ReadyReplicas Observed ready replica count. Nullable until first status update.
	ReadyReplicas *int `json:"ready_replicas,omitempty"`

	// Replicas Desired replica count. Nullable; DaemonSet has no scalar desired count.
	Replicas *int `json:"replicas,omitempty"`

	// Spec Kind-specific fields the collector chooses to persist (e.g. strategy
	// for Deployment, service_name for StatefulSet). Open-ended; stored
	// as JSONB.
	Spec      *map[string]interface{} `json:"spec,omitempty"`
	UpdatedAt *time.Time              `json:"updated_at,omitempty"`
}

// WorkloadCreate defines model for WorkloadCreate.
type WorkloadCreate struct {
	// Containers Containers associated with the resource. For Pods this reflects the
	// live runtime (name, image, image_id from containerStatuses, init
	// flag); for Workloads it's the pod template's declared containers
	// (name, image, init). Opaque in v1: each entry's shape is additive,
	// so new collector-extracted fields don't require a spec bump.
	Containers *ContainerList `json:"containers,omitempty"`

	// Kind Workload kind discriminator. Immutable after creation.
	Kind WorkloadKind `json:"kind"`

	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`

	// Name Kubernetes workload name (DNS-subdomain style). Unique per
	// (namespace, kind). Immutable after creation.
	Name string `json:"name"`

	// NamespaceId Parent namespace id. Immutable after creation; the namespace
	// must already exist or the create returns 404.
	NamespaceId openapi_types.UUID `json:"namespace_id"`

	// ReadyReplicas Observed ready replica count. Nullable until first status update.
	ReadyReplicas *int `json:"ready_replicas,omitempty"`

	// Replicas Desired replica count. Nullable; DaemonSet has no scalar desired count.
	Replicas *int `json:"replicas,omitempty"`

	// Spec Kind-specific fields the collector chooses to persist (e.g. strategy
	// for Deployment, service_name for StatefulSet). Open-ended; stored
	// as JSONB.
	Spec *map[string]interface{} `json:"spec,omitempty"`
}

// WorkloadKind Kubernetes workload controller kind. Casing matches the `kind` field
// Kubernetes itself emits. Additional kinds (Job, CronJob, ReplicaSet,
// ReplicationController) may be introduced as new enum values without a
// schema migration (see ADR-0003).
type WorkloadKind string

// WorkloadList Paged list of workloads.
type WorkloadList struct {
	Items []Workload `json:"items"`

	// NextCursor Opaque cursor to pass as `?cursor=` to fetch the next page.
	// Absent or null when no more pages remain.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// WorkloadMutable Fields on a Workload that clients may set and later update.
type WorkloadMutable struct {
	// Containers Containers associated with the resource. For Pods this reflects the
	// live runtime (name, image, image_id from containerStatuses, init
	// flag); for Workloads it's the pod template's declared containers
	// (name, image, init). Opaque in v1: each entry's shape is additive,
	// so new collector-extracted fields don't require a spec bump.
	Containers *ContainerList `json:"containers,omitempty"`

	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`

	// ReadyReplicas Observed ready replica count. Nullable until first status update.
	ReadyReplicas *int `json:"ready_replicas,omitempty"`

	// Replicas Desired replica count. Nullable; DaemonSet has no scalar desired count.
	Replicas *int `json:"replicas,omitempty"`

	// Spec Kind-specific fields the collector chooses to persist (e.g. strategy
	// for Deployment, service_name for StatefulSet). Open-ended; stored
	// as JSONB.
	Spec *map[string]interface{} `json:"spec,omitempty"`
}

// WorkloadUpdate Fields on a Workload that clients may set and later update.
type WorkloadUpdate = WorkloadMutable

// ClusterId defines model for ClusterId.
type ClusterId = openapi_types.UUID

// Cursor defines model for Cursor.
type Cursor = string

// IngressId defines model for IngressId.
type IngressId = openapi_types.UUID

// IngressNamespaceIdFilter defines model for IngressNamespaceIdFilter.
type IngressNamespaceIdFilter = openapi_types.UUID

// Limit defines model for Limit.
type Limit = int

// NamespaceClusterIdFilter defines model for NamespaceClusterIdFilter.
type NamespaceClusterIdFilter = openapi_types.UUID

// NamespaceId defines model for NamespaceId.
type NamespaceId = openapi_types.UUID

// NodeClusterIdFilter defines model for NodeClusterIdFilter.
type NodeClusterIdFilter = openapi_types.UUID

// NodeId defines model for NodeId.
type NodeId = openapi_types.UUID

// PodId defines model for PodId.
type PodId = openapi_types.UUID

// PodNamespaceIdFilter defines model for PodNamespaceIdFilter.
type PodNamespaceIdFilter = openapi_types.UUID

// ServiceId defines model for ServiceId.
type ServiceId = openapi_types.UUID

// ServiceNamespaceIdFilter defines model for ServiceNamespaceIdFilter.
type ServiceNamespaceIdFilter = openapi_types.UUID

// WorkloadId defines model for WorkloadId.
type WorkloadId = openapi_types.UUID

// WorkloadKindFilter Kubernetes workload controller kind. Casing matches the `kind` field
// Kubernetes itself emits. Additional kinds (Job, CronJob, ReplicaSet,
// ReplicationController) may be introduced as new enum values without a
// schema migration (see ADR-0003).
type WorkloadKindFilter = WorkloadKind

// WorkloadNamespaceIdFilter defines model for WorkloadNamespaceIdFilter.
type WorkloadNamespaceIdFilter = openapi_types.UUID

// BadRequest RFC 7807 problem details.
type BadRequest = Problem

// Conflict RFC 7807 problem details.
type Conflict = Problem

// Forbidden RFC 7807 problem details.
type Forbidden = Problem

// NotFound RFC 7807 problem details.
type NotFound = Problem

// Unauthorized RFC 7807 problem details.
type Unauthorized = Problem

// ListClustersParams defines parameters for ListClusters.
type ListClustersParams struct {
	// Limit Maximum number of items to return. Server clamps to [1, 200].
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque cursor returned from a previous list response.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ListIngressesParams defines parameters for ListIngresses.
type ListIngressesParams struct {
	// Limit Maximum number of items to return. Server clamps to [1, 200].
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque cursor returned from a previous list response.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// NamespaceId Return only ingresses belonging to this namespace.
	NamespaceId *IngressNamespaceIdFilter `form:"namespace_id,omitempty" json:"namespace_id,omitempty"`
}

// ListNamespacesParams defines parameters for ListNamespaces.
type ListNamespacesParams struct {
	// Limit Maximum number of items to return. Server clamps to [1, 200].
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque cursor returned from a previous list response.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// ClusterId Return only namespaces belonging to this cluster.
	ClusterId *NamespaceClusterIdFilter `form:"cluster_id,omitempty" json:"cluster_id,omitempty"`
}

// ListNodesParams defines parameters for ListNodes.
type ListNodesParams struct {
	// Limit Maximum number of items to return. Server clamps to [1, 200].
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque cursor returned from a previous list response.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// ClusterId Return only nodes belonging to this cluster.
	ClusterId *NodeClusterIdFilter `form:"cluster_id,omitempty" json:"cluster_id,omitempty"`
}

// ListPodsParams defines parameters for ListPods.
type ListPodsParams struct {
	// Limit Maximum number of items to return. Server clamps to [1, 200].
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque cursor returned from a previous list response.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// NamespaceId Return only pods belonging to this namespace.
	NamespaceId *PodNamespaceIdFilter `form:"namespace_id,omitempty" json:"namespace_id,omitempty"`
}

// ListServicesParams defines parameters for ListServices.
type ListServicesParams struct {
	// Limit Maximum number of items to return. Server clamps to [1, 200].
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque cursor returned from a previous list response.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// NamespaceId Return only services belonging to this namespace.
	NamespaceId *ServiceNamespaceIdFilter `form:"namespace_id,omitempty" json:"namespace_id,omitempty"`
}

// ListWorkloadsParams defines parameters for ListWorkloads.
type ListWorkloadsParams struct {
	// Limit Maximum number of items to return. Server clamps to [1, 200].
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque cursor returned from a previous list response.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// NamespaceId Return only workloads belonging to this namespace.
	NamespaceId *WorkloadNamespaceIdFilter `form:"namespace_id,omitempty" json:"namespace_id,omitempty"`

	// Kind Return only workloads of this kind.
	Kind *WorkloadKindFilter `form:"kind,omitempty" json:"kind,omitempty"`
}

// CreateClusterJSONRequestBody defines body for CreateCluster for application/json ContentType.
type CreateClusterJSONRequestBody = ClusterCreate

// UpdateClusterApplicationMergePatchPlusJSONRequestBody defines body for UpdateCluster for application/merge-patch+json ContentType.
type UpdateClusterApplicationMergePatchPlusJSONRequestBody = ClusterUpdate

// CreateIngressJSONRequestBody defines body for CreateIngress for application/json ContentType.
type CreateIngressJSONRequestBody = IngressCreate

// UpdateIngressApplicationMergePatchPlusJSONRequestBody defines body for UpdateIngress for application/merge-patch+json ContentType.
type UpdateIngressApplicationMergePatchPlusJSONRequestBody = IngressUpdate

// CreateNamespaceJSONRequestBody defines body for CreateNamespace for application/json ContentType.
type CreateNamespaceJSONRequestBody = NamespaceCreate

// UpdateNamespaceApplicationMergePatchPlusJSONRequestBody defines body for UpdateNamespace for application/merge-patch+json ContentType.
type UpdateNamespaceApplicationMergePatchPlusJSONRequestBody = NamespaceUpdate

// CreateNodeJSONRequestBody defines body for CreateNode for application/json ContentType.
type CreateNodeJSONRequestBody = NodeCreate

// UpdateNodeApplicationMergePatchPlusJSONRequestBody defines body for UpdateNode for application/merge-patch+json ContentType.
type UpdateNodeApplicationMergePatchPlusJSONRequestBody = NodeUpdate

// CreatePodJSONRequestBody defines body for CreatePod for application/json ContentType.
type CreatePodJSONRequestBody = PodCreate

// UpdatePodApplicationMergePatchPlusJSONRequestBody defines body for UpdatePod for application/merge-patch+json ContentType.
type UpdatePodApplicationMergePatchPlusJSONRequestBody = PodUpdate

// CreateServiceJSONRequestBody defines body for CreateService for application/json ContentType.
type CreateServiceJSONRequestBody = ServiceCreate

// UpdateServiceApplicationMergePatchPlusJSONRequestBody defines body for UpdateService for application/merge-patch+json ContentType.
type UpdateServiceApplicationMergePatchPlusJSONRequestBody = ServiceUpdate

// CreateWorkloadJSONRequestBody defines body for CreateWorkload for application/json ContentType.
type CreateWorkloadJSONRequestBody = WorkloadCreate

// UpdateWorkloadApplicationMergePatchPlusJSONRequestBody defines body for UpdateWorkload for application/merge-patch+json ContentType.
type UpdateWorkloadApplicationMergePatchPlusJSONRequestBody = WorkloadUpdate

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Liveness probe
	// (GET /healthz)
	GetHealthz(w http.ResponseWriter, r *http.Request)
	// Readiness probe
	// (GET /readyz)
	GetReadyz(w http.ResponseWriter, r *http.Request)
	// List clusters
	// (GET /v1/clusters)
	ListClusters(w http.ResponseWriter, r *http.Request, params ListClustersParams)
	// Register a cluster
	// (POST /v1/clusters)
	CreateCluster(w http.ResponseWriter, r *http.Request)
	// Delete a cluster
	// (DELETE /v1/clusters/{id})
	DeleteCluster(w http.ResponseWriter, r *http.Request, id ClusterId)
	// Get a cluster
	// (GET /v1/clusters/{id})
	GetCluster(w http.ResponseWriter, r *http.Request, id ClusterId)
	// Update mutable fields of a cluster
	// (PATCH /v1/clusters/{id})
	UpdateCluster(w http.ResponseWriter, r *http.Request, id ClusterId)
	// List ingresses
	// (GET /v1/ingresses)
	ListIngresses(w http.ResponseWriter, r *http.Request, params ListIngressesParams)
	// Register an ingress
	// (POST /v1/ingresses)
	CreateIngress(w http.ResponseWriter, r *http.Request)
	// Delete an ingress
	// (DELETE /v1/ingresses/{id})
	DeleteIngress(w http.ResponseWriter, r *http.Request, id IngressId)
	// Get an ingress
	// (GET /v1/ingresses/{id})
	GetIngress(w http.ResponseWriter, r *http.Request, id IngressId)
	// Update mutable fields of an ingress
	// (PATCH /v1/ingresses/{id})
	UpdateIngress(w http.ResponseWriter, r *http.Request, id IngressId)
	// List namespaces
	// (GET /v1/namespaces)
	ListNamespaces(w http.ResponseWriter, r *http.Request, params ListNamespacesParams)
	// Register a namespace
	// (POST /v1/namespaces)
	CreateNamespace(w http.ResponseWriter, r *http.Request)
	// Delete a namespace
	// (DELETE /v1/namespaces/{id})
	DeleteNamespace(w http.ResponseWriter, r *http.Request, id NamespaceId)
	// Get a namespace
	// (GET /v1/namespaces/{id})
	GetNamespace(w http.ResponseWriter, r *http.Request, id NamespaceId)
	// Update mutable fields of a namespace
	// (PATCH /v1/namespaces/{id})
	UpdateNamespace(w http.ResponseWriter, r *http.Request, id NamespaceId)
	// List nodes
	// (GET /v1/nodes)
	ListNodes(w http.ResponseWriter, r *http.Request, params ListNodesParams)
	// Register a node
	// (POST /v1/nodes)
	CreateNode(w http.ResponseWriter, r *http.Request)
	// Delete a node
	// (DELETE /v1/nodes/{id})
	DeleteNode(w http.ResponseWriter, r *http.Request, id NodeId)
	// Get a node
	// (GET /v1/nodes/{id})
	GetNode(w http.ResponseWriter, r *http.Request, id NodeId)
	// Update mutable fields of a node
	// (PATCH /v1/nodes/{id})
	UpdateNode(w http.ResponseWriter, r *http.Request, id NodeId)
	// List pods
	// (GET /v1/pods)
	ListPods(w http.ResponseWriter, r *http.Request, params ListPodsParams)
	// Register a pod
	// (POST /v1/pods)
	CreatePod(w http.ResponseWriter, r *http.Request)
	// Delete a pod
	// (DELETE /v1/pods/{id})
	DeletePod(w http.ResponseWriter, r *http.Request, id PodId)
	// Get a pod
	// (GET /v1/pods/{id})
	GetPod(w http.ResponseWriter, r *http.Request, id PodId)
	// Update mutable fields of a pod
	// (PATCH /v1/pods/{id})
	UpdatePod(w http.ResponseWriter, r *http.Request, id PodId)
	// List services
	// (GET /v1/services)
	ListServices(w http.ResponseWriter, r *http.Request, params ListServicesParams)
	// Register a service
	// (POST /v1/services)
	CreateService(w http.ResponseWriter, r *http.Request)
	// Delete a service
	// (DELETE /v1/services/{id})
	DeleteService(w http.ResponseWriter, r *http.Request, id ServiceId)
	// Get a service
	// (GET /v1/services/{id})
	GetService(w http.ResponseWriter, r *http.Request, id ServiceId)
	// Update mutable fields of a service
	// (PATCH /v1/services/{id})
	UpdateService(w http.ResponseWriter, r *http.Request, id ServiceId)
	// List workloads
	// (GET /v1/workloads)
	ListWorkloads(w http.ResponseWriter, r *http.Request, params ListWorkloadsParams)
	// Register a workload
	// (POST /v1/workloads)
	CreateWorkload(w http.ResponseWriter, r *http.Request)
	// Delete a workload
	// (DELETE /v1/workloads/{id})
	DeleteWorkload(w http.ResponseWriter, r *http.Request, id WorkloadId)
	// Get a workload
	// (GET /v1/workloads/{id})
	GetWorkload(w http.ResponseWriter, r *http.Request, id WorkloadId)
	// Update mutable fields of a workload
	// (PATCH /v1/workloads/{id})
	UpdateWorkload(w http.ResponseWriter, r *http.Request, id WorkloadId)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReadyz operation middleware
func (siw *ServerInterfaceWrapper) GetReadyz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReadyz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListClusters operation middleware
func (siw *ServerInterfaceWrapper) ListClusters(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"read"})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListClustersParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListClusters(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateCluster operation middleware
func (siw *ServerInterfaceWrapper) CreateCluster(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"write"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCluster(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteCluster operation middleware
func (siw *ServerInterfaceWrapper) DeleteCluster(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ClusterId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"delete"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteCluster(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCluster operation middleware
func (siw *ServerInterfaceWrapper) GetCluster(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ClusterId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"read"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCluster(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateCluster operation middleware
func (siw *ServerInterfaceWrapper) UpdateCluster(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ClusterId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"write"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateCluster(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListIngresses operation middleware
func (siw *ServerInterfaceWrapper) ListIngresses(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"read"})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListIngressesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		return
	}

	// ------------- Optional query parameter "namespace_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "namespace_id", r.URL.Query(), &params.NamespaceId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListIngresses(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateIngress operation middleware
func (siw *ServerInterfaceWrapper) CreateIngress(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"write"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateIngress(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteIngress operation middleware
func (siw *ServerInterfaceWrapper) DeleteIngress(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IngressId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"delete"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteIngress(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetIngress operation middleware
func (siw *ServerInterfaceWrapper) GetIngress(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IngressId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"read"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetIngress(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateIngress operation middleware
func (siw *ServerInterfaceWrapper) UpdateIngress(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IngressId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"write"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateIngress(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListNamespaces operation middleware
func (siw *ServerInterfaceWrapper) ListNamespaces(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"read"})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListNamespacesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		return
	}

	// ------------- Optional query parameter "cluster_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cluster_id", r.URL.Query(), &params.ClusterId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cluster_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListNamespaces(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateNamespace operation middleware
func (siw *ServerInterfaceWrapper) CreateNamespace(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"write"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateNamespace(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteNamespace operation middleware
func (siw *ServerInterfaceWrapper) DeleteNamespace(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id NamespaceId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"delete"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteNamespace(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetNamespace operation middleware
func (siw *ServerInterfaceWrapper) GetNamespace(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id NamespaceId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"read"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetNamespace(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateNamespace operation middleware
func (siw *ServerInterfaceWrapper) UpdateNamespace(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id NamespaceId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"write"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateNamespace(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListNodes operation middleware
func (siw *ServerInterfaceWrapper) ListNodes(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"read"})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListNodesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		return
	}

	// ------------- Optional query parameter "cluster_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cluster_id", r.URL.Query(), &params.ClusterId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cluster_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListNodes(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateNode operation middleware
func (siw *ServerInterfaceWrapper) CreateNode(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"write"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateNode(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteNode operation middleware
func (siw *ServerInterfaceWrapper) DeleteNode(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id NodeId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"delete"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteNode(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetNode operation middleware
func (siw *ServerInterfaceWrapper) GetNode(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id NodeId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"read"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetNode(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateNode operation middleware
func (siw *ServerInterfaceWrapper) UpdateNode(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id NodeId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"write"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateNode(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListPods operation middleware
func (siw *ServerInterfaceWrapper) ListPods(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"read"})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListPodsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		return
	}

	// ------------- Optional query parameter "namespace_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "namespace_id", r.URL.Query(), &params.NamespaceId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPods(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreatePod operation middleware
func (siw *ServerInterfaceWrapper) CreatePod(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"write"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreatePod(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeletePod operation middleware
func (siw *ServerInterfaceWrapper) DeletePod(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id PodId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"delete"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeletePod(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPod operation middleware
func (siw *ServerInterfaceWrapper) GetPod(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id PodId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"read"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPod(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdatePod operation middleware
func (siw *ServerInterfaceWrapper) UpdatePod(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id PodId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"write"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdatePod(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListServices operation middleware
func (siw *ServerInterfaceWrapper) ListServices(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"read"})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListServicesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		return
	}

	// ------------- Optional query parameter "namespace_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "namespace_id", r.URL.Query(), &params.NamespaceId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListServices(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateService operation middleware
func (siw *ServerInterfaceWrapper) CreateService(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"write"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateService(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteService operation middleware
func (siw *ServerInterfaceWrapper) DeleteService(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ServiceId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"delete"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteService(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetService operation middleware
func (siw *ServerInterfaceWrapper) GetService(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ServiceId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"read"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetService(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateService operation middleware
func (siw *ServerInterfaceWrapper) UpdateService(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ServiceId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"write"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateService(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListWorkloads operation middleware
func (siw *ServerInterfaceWrapper) ListWorkloads(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"read"})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListWorkloadsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		return
	}

	// ------------- Optional query parameter "namespace_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "namespace_id", r.URL.Query(), &params.NamespaceId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace_id", Err: err})
		return
	}

	// ------------- Optional query parameter "kind" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "kind", r.URL.Query(), &params.Kind, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "kind", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListWorkloads(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateWorkload operation middleware
func (siw *ServerInterfaceWrapper) CreateWorkload(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"write"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateWorkload(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteWorkload operation middleware
func (siw *ServerInterfaceWrapper) DeleteWorkload(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id WorkloadId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"delete"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteWorkload(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWorkload operation middleware
func (siw *ServerInterfaceWrapper) GetWorkload(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id WorkloadId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"read"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWorkload(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateWorkload operation middleware
func (siw *ServerInterfaceWrapper) UpdateWorkload(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id WorkloadId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"write"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateWorkload(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/healthz", wrapper.GetHealthz)
	m.HandleFunc("GET "+options.BaseURL+"/readyz", wrapper.GetReadyz)
	m.HandleFunc("GET "+options.BaseURL+"/v1/clusters", wrapper.ListClusters)
	m.HandleFunc("POST "+options.BaseURL+"/v1/clusters", wrapper.CreateCluster)
	m.HandleFunc("DELETE "+options.BaseURL+"/v1/clusters/{id}", wrapper.DeleteCluster)
	m.HandleFunc("GET "+options.BaseURL+"/v1/clusters/{id}", wrapper.GetCluster)
	m.HandleFunc("PATCH "+options.BaseURL+"/v1/clusters/{id}", wrapper.UpdateCluster)
	m.HandleFunc("GET "+options.BaseURL+"/v1/ingresses", wrapper.ListIngresses)
	m.HandleFunc("POST "+options.BaseURL+"/v1/ingresses", wrapper.CreateIngress)
	m.HandleFunc("DELETE "+options.BaseURL+"/v1/ingresses/{id}", wrapper.DeleteIngress)
	m.HandleFunc("GET "+options.BaseURL+"/v1/ingresses/{id}", wrapper.GetIngress)
	m.HandleFunc("PATCH "+options.BaseURL+"/v1/ingresses/{id}", wrapper.UpdateIngress)
	m.HandleFunc("GET "+options.BaseURL+"/v1/namespaces", wrapper.ListNamespaces)
	m.HandleFunc("POST "+options.BaseURL+"/v1/namespaces", wrapper.CreateNamespace)
	m.HandleFunc("DELETE "+options.BaseURL+"/v1/namespaces/{id}", wrapper.DeleteNamespace)
	m.HandleFunc("GET "+options.BaseURL+"/v1/namespaces/{id}", wrapper.GetNamespace)
	m.HandleFunc("PATCH "+options.BaseURL+"/v1/namespaces/{id}", wrapper.UpdateNamespace)
	m.HandleFunc("GET "+options.BaseURL+"/v1/nodes", wrapper.ListNodes)
	m.HandleFunc("POST "+options.BaseURL+"/v1/nodes", wrapper.CreateNode)
	m.HandleFunc("DELETE "+options.BaseURL+"/v1/nodes/{id}", wrapper.DeleteNode)
	m.HandleFunc("GET "+options.BaseURL+"/v1/nodes/{id}", wrapper.GetNode)
	m.HandleFunc("PATCH "+options.BaseURL+"/v1/nodes/{id}", wrapper.UpdateNode)
	m.HandleFunc("GET "+options.BaseURL+"/v1/pods", wrapper.ListPods)
	m.HandleFunc("POST "+options.BaseURL+"/v1/pods", wrapper.CreatePod)
	m.HandleFunc("DELETE "+options.BaseURL+"/v1/pods/{id}", wrapper.DeletePod)
	m.HandleFunc("GET "+options.BaseURL+"/v1/pods/{id}", wrapper.GetPod)
	m.HandleFunc("PATCH "+options.BaseURL+"/v1/pods/{id}", wrapper.UpdatePod)
	m.HandleFunc("GET "+options.BaseURL+"/v1/services", wrapper.ListServices)
	m.HandleFunc("POST "+options.BaseURL+"/v1/services", wrapper.CreateService)
	m.HandleFunc("DELETE "+options.BaseURL+"/v1/services/{id}", wrapper.DeleteService)
	m.HandleFunc("GET "+options.BaseURL+"/v1/services/{id}", wrapper.GetService)
	m.HandleFunc("PATCH "+options.BaseURL+"/v1/services/{id}", wrapper.UpdateService)
	m.HandleFunc("GET "+options.BaseURL+"/v1/workloads", wrapper.ListWorkloads)
	m.HandleFunc("POST "+options.BaseURL+"/v1/workloads", wrapper.CreateWorkload)
	m.HandleFunc("DELETE "+options.BaseURL+"/v1/workloads/{id}", wrapper.DeleteWorkload)
	m.HandleFunc("GET "+options.BaseURL+"/v1/workloads/{id}", wrapper.GetWorkload)
	m.HandleFunc("PATCH "+options.BaseURL+"/v1/workloads/{id}", wrapper.UpdateWorkload)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x97XLbuNX/rWD478zaW0pWnJfuOvOfTjZpuu5mE02cPP0Q5bEh4khCTQJcAJSj7nim",
	"F9Er7JU8cwCCLxIlUn5RE9tfEksCgcPz+jvA4eHvQSSTVAoQRgdHvwcpVTQBA8p+ehln2oA6ZviBgY4U",
	"Tw2XIjgKTkDNQfWo1nwqgJHIDSWcgTB8wkH1gzDgODSlZhaEgaAJBEcBZ0EYKPgt4wpYcGRUBmGgoxkk",
	"FFeZSJVQExwFWWZHmkWKV2mjuJgGl5dh8DJTWqpVit6l9LcMSGR/JgpMppCwiZIJoSRVMOcy0yTm2hAF",
	"OpVCQ0HjbxmoRUmkmySoEpbQL29ATM0sOHr66LCJsGMxVaB1F25xN3QH3MqJeksT0CmN4Ji95rGBBv69",
	"txwjUsQLTx9oMoZYiikXU2IkMTOuifBTrWNeMeDU0rQNtW94ws0qab/SLzzJEiKyZAyKyAnhBhKNJDk5",
	"94njMIlimqT2h0+PQnI4GHxeR2Vsl6qSx2BCs9gER08HIYoblwyODgf4iQv36VFBNRcGpqAs2QV3C4Pp",
	"wuSCT01czu1prYK6n7fncEUR2tW0oHAHivpWsi3ZJ9luOSdZN6ZJtgt+DSXrQk0q2W6I2dLDpJLt2rkg",
	"a3g3xddu6A44lxO1Jfdy+nbNwb9LdR5L2knxLvKxO+ChJ+sXLjpxz5OmMZJYpp1zwdbxC3+r8ekPCibB",
	"UfD/DkrodOB+1QdVUmq0bSngksRdSvgS5eCQkcV/P1H2Hn7LQNuYHElhQNg/aZrGPKJI+EGq5DiG5I//",
	"0HgXv3dk1NBd5RZdjvYxEgqMKLd4P0DYJ8Uk5tFOKfFrkgtuZogsFQhDtKEGyB70p/2QsMytD1Ys+5bU",
	"11KNOWMgdknrB3kOgnBN5jTmjIwzQ2IanWtiZkB0JFMg3sbIeGG/lSkoS42l+q00r2Um2C6Jfg9aZioC",
	"IqQhE1zdkvJR0MzMpOL/hJ2S8yvXGi1NKsJFzkegChQxyN2+teh8nkp+ZOmK43eT4OjT5rXzC37NDB3H",
	"EFyGvwepQjEY7iwuUkANsFNqavbKqIGe4QlYT0nZOxEvvKdcMuIQ/WmDrbdeFtPFNrfyxg6//LzMwxfx",
	"BV1ocsbFRFFtVBaZTMFpLKc8ovEZmUhFcjYgajdeGbWNH/0VSi+9W6ulYM+eWFDuPx6GGFMMKKTgfz/R",
	"3j8HvR8/5//3Pv8+CJ8dXvqv/xA03H2Wsmsy/rIaxD65qGYp96wNq9Ktrfi5mEyO/wGRaWIr+SUbgxJg",
	"oIC4RMGU4x82o7RcfPnrq5+cu3RDXtoVb1BBvSyWgr8dTnScTXsxP68Cp5BkgmNiTiMltS6pHInjJHHr",
	"EDrB27HsQXc0EkF4i9JekpS9pQ4iGNKFBTQ263SMJ5QIuChTjpLxb7huSGSHdArMbUHIib9Mo9LXuWzT",
	"29ofHYSGq+f3QJWiC/ws4Is5jTrtmBhJUqo1oZqc/dl99//P8NsJmGhm5YazkZROoT8SL8Yag6FURGRx",
	"TC5mIIiQJJEK7BBNFCSU58LEMVajutmOvetVkRTc9fq5ckuvOcSI6wSh3ssQM6OGRDFHnpGEIno2hApG",
	"Yoo/OztclQFN+SkIlkouGiRZscYXw+Pce5GP79+QPS6c++BS0HgfJy59seJNzodxncZ0cdpsXD9nCRW9",
	"ieIgWLwgMR1DHJKJAujhxP26rRw+fdawAog5V1Ik0HQvr/1UpDKMGDotQA7MQ4Q9CENDkirJ9vurFrqy",
	"6HnBo9M5KM1dlF6CWLmQKkzMxxIFqVTGwZUKuy1NZBQ86h/+2H86CpZJeXzYGNzGEDuxMsadaIY1cbey",
	"cMkfqzE3iqoFyTSons4Ql2DmaMeTc1gczGmcgROXzmmsLllhWanfqZJzzpqyg4+CgYoXOHmFGYzjguMM",
	"B6EtzqQ2OMTP0x+JdymIHggG7DmJZJJIQSxl+ohMzyEkcK5DQvEfmYLQMz4xIVH4C8qPsiQkUqQK8H8z",
	"s1N2kD16SCfvzSMv1xv5R2uYV49dKw78V1BT6KUU3dlYskWfYDgnPghNrO94Ts7QDM8QSnMfoJCNCTeo",
	"jG4UoQpIDBNDMhHNqJgCQ764PMVQLtZFgOJndLRaRhwxgMsv0MOqHBD3yWupyFAy7XI+BZMYImPD50jE",
	"fA5EZQKBCdlDckPCEzr1/53yfN878qudGGoyDTokXHAzEpOYTvefWzD29yLV5OY7F59TyYiBJEUH+Z0m",
	"DKKYIsgoptMjsbSs4Ga/T/KIwgWZPzoiQKMZAWHU4jtN9IymgEx1BjiHcCS0dOFTxnhzUvXgi1E0qrCZ",
	"SfGd8YkLoUSnEJFxlqROC4vw2GzVtVhT6tdykPwZaIzquYx1tGUa/gUiSzAwyfNKVCqVfa13+ynjMSsc",
	"mt1tsIITaKNUTaW22w6bo2FORlM4zHf3u9tIfsF9SECKTHEOLuvI7x2zDiAvXr3vDQaDJ50Tjsc1CPqo",
	"EYLuferlf33vv9r/c2O6Uduiad+Zuc38pLJTdEvpSs74TelKPmTbdKVVnZsRVYU2fxKHA8neq7cnPRuw",
	"iTaLGPb75KNLXlJQlX23bVKX29Wb5fTCblBVj236ZB2pzx2k92NHIsm0ITRGNVoQ+GKTFGUHOUXIz9o0",
	"eTJ44u6zfWt2Oc9aVrZrpV1edhlCI/yu3BgtVapLIlYcd143E/P++B5kYkumtykTE4UHuGIqlsvnNIqp",
	"1muyJO9BcIizZqu5UhiF8EKRMRfMngznSc0oEFMuvowC/NMoChN+vppNHD59/A2nEyqLHTmNvCJKZjZb",
	"sMPWozcSUaU4aHIxowbmNqWGkShgG4lmUoNVW0Q62pA9zENCklIzc/+eImkhGdPoHERxvjYSVlAHBBO9",
	"/ZuEdCZuuO0Pb05QISZ8mrl9b3t7vNOt4w3pkUBddTh9AgpEBIycQKTAOd2bu4PL9Ra3bVq0HCOvlRZ5",
	"/31mrTbPlKiCkShzJdI1VXrjAd+SLbw9OTlGxhs5VTSdLYgFJJbvVKPHcGdiaMw1MHdoYZ7VzXMuWM/I",
	"nrsyoWlqEbeXXr45A2QMM55/qfkXP1wyiJ0sPfCHSOqFNpAEYTDONBfo5cOggjHxE0u4wITcTm8P55r2",
	"wFd/SGcLbX9pSi6Kk8PuIi8u2YDzyzKILvDzfpxLFHy7zsnEzQK+28H9tSKYW0L9JQrdgPvLyqktkf/W",
	"Kt6IlMuqxTac7EciSB6Jm0TJYXuSUrKyQ5riDyP+W0nKkr6tqtq1MH/JCo/6q4cvhVZ0Qf1l/d11YX/p",
	"ou8B8F+xvI2HMMXoq2L/2z8b+WbOBmZUd/UTdizqUUxR2cc2hrHi7ORFhJDFpT4fQCVcUEwEMP2pHhig",
	"6tHIHhqgcAgVC1LyyC2iSW03xSjJMjSpZR/z+LDT3n+hL9vC3NWAcGWgW7qsG4G5byXb5j4ke4BtrbDN",
	"I+Yct0l2Hchmc/zW+oIi/vXvMmiTbDNek2x7qLaFRn/TKA15VwI0nY2ZxPB7QyDthrX0lmEa8qIRoUnW",
	"DZxJdgO4DD3vfYBkFQvbjMZQLFeth1HRjBuw/rfhXHv4kVRH9MmGugOasGdPQkJVgv+lafTsSQwh0Y9/",
	"HHzpAhx2UTFzno0hBrO+cuUXN4BMuSlOeKluq1qZ38myFalPbSHAKpesxr07cXUCfhnPjI/jTJiMHB72",
	"B0/6j8mbDydNG/DPugFHybbHjNXI9LXAxaFk3e9gKNm9PMsfSnaDgO/RdQHfvTrOTyXbBBGHkm2LEDdq",
	"cSvuQno6wq4rHeHfurbc60N8lF7zAf5Qsi5IMZXs2kARfe49wIkVO9sIE4eSXRUlliWCrVXrtULJbwjs",
	"YGqyBni+RTeUl/kJh7VdNSXXBO+bZTEwIkWnIoP2/T6cuXmn74gMQTBbrv3elRuG5CSLIgAGLByJ15TH",
	"wEJUwI/iXMgLUQXsnfb9ugH1VLJTnjbYsGTkeIiz2kqEvePh/AlSczycP9vvk+NqDf1z+3iYfR7LVstS",
	"TagYieMhibkBReMVUp48bSDFP1PZ6HU/yLQXwxzioh42twBXQJKX4SLD915BGsuFrZE/GIkTQw1MshjB",
	"yAF5RSGR4gTMfp98sPUnvkbigsb5w3i//KBHyHFQ730VAYlmGLH+869/W3RTrtDDccw9LZ0XAmsZz0GP",
	"BHKwN8oGg8dA3oPFR0iD/6qco0/eoo/Bie08tthYyJGoFMcggfg1FcRSZp+IzStUCZOgxXfGnYuTBZiR",
	"yGto/ibHIXmppPibHO83h5N239XkprZF8lUE8fUUOPhHDVcf9X39kvzph8GfSP4II2FgKI8b4pj7Af9a",
	"faZDKan0Gk+eK3NuNLbWxQ4PXazJATXeTbVipb62vb3GpRPQOk/3NsciN0V5wecOtTtcaEOFq3doe3Km",
	"LNEuGnY8/fHHasOOwWC1ZUcYGG5iaLw190WlG0hAxzIzR+OYivPWZ3mWbt/+6lcLN1Vy530Aumt8fsG9",
	"zP7ye/96qjTuVf6Xc39TDpgP2TYPbNXp1lzQN+54KOf+9jJBL7vmbDDXjS4Zoe+Oct2s0Pvke5AZLlne",
	"xuzQ2/9VM0S/XdqQFbzw3WN8J6gh2YMkNQvr9n8GymLMFg7IX76g0dHYJlxe3stbx41ZwDdT7SGV0c1t",
	"dpD59ucbLdl2z/PhvCExVE3BnLoPqZJGRjIObUp7euO12hocTTcoE8yNcsefT953D1MmmASgWJAni4pw",
	"EMO7scC6ishDxQ4+5AMObUx2qgM2RbbC6hYp9MlLahuV2NsBl1aCyJJaLY7REE9GAhLuNKXI7qnJm8Ig",
	"ib64up7xTzKTKSiSfv18JGZUMEwVqykFZulRvv78EdHZWIOpV04Xlhy4M5qhVIg/3kjKfqIx4nzEJlV7",
	"bqyCzm9/27xwGVF8Pbmh32bofi/+iq8S8tsuWVs1x7r9NMGv93BS1JYp5D3ObilhKFrBVTacNiQPXmzb",
	"Zg/t9uGVdLv5nLqu3GKxT2i3yhjH32whJQabTQlFl1qigmXdDrbyx/GtRENL0P5mGh4OuDqmNVXLuFZ2",
	"U0i0Ob2pKVsnzagYk21f2IQJzvCXMxeLRmIFHJAcG7wo9/bP7VOSe9WN3bCyvRyORP4Bx78sSNi3CcAY",
	"ygpgu02PN25xiav8sXvMMjOEjkSOPhI+zZ/F29Plk1yP9+sgotzMDsKgsuMehEGx494IGzxbu6SNRc/F",
	"6+aNRWi/B4njstPdmDkuHa08HC42PLGLfu1UORtryP/e+VJ+5wDzgSSSmT/osU40E4bHZMKVdv0qM11h",
	"arE53rg1vn7tV6Bt+8g1iz4vT7/IDI1fEh3RmCrC8gvdBa0U6BSitqxyyT9ywXp4GZ/wyENvUzt/i2ZS",
	"atC1lNeWodnnNWG6GIn60Vvo9xXsWa/bdy49z369wFEbqYCNBNXkbyfv3v7kjGxJupcb7GfbxGYF7NxM",
	"ZhPmISNEaxyJMschW6c4NrOPMsXN4gSJzlvK2n6aLzLXb8d113ztA7TtshmsWNrw2PXfJFzrDBiRmenJ",
	"SW9MhYX2woaasxd5y1AbTY6IW4jY09DIXu4ORs/6IzESJ5FMQZOposLk591ujaORIKRHztC8zgixR7I2",
	"QKB3moIpm6bqfOSF4gbO3MgcguBYZ25kjyfoF7SfMc+9I4pR8zvtcCPgfPv5fAxiwAlxPgWJnJddofyS",
	"9kHjfEkax77igI7lHJ7jaOciUGWLRD7homdbC/uedhr5YLvGartbZFuLWdCQT++axlr6I27iBdHUcD1Z",
	"2HKAekfZkRgv7Nlx0VHW6r9VVtR3J+fSImbGpK4BKxcT2XA++peTD7YlHN7C99+/UFOpv/8+JNRmCfbb",
	"CpipdK3ThMZ5/+m8pdZIuOfJTyB6myUvY5kxsnfy9uU++S2jMfoLBz8miiaAEMDqx4cZ10VV796g/6g/",
	"2LfNq+w5PnJKn6OcpCCRnAO6/Fxz3vA5CMCwLZyTts+K24PeQn75nshZIVjy8v3HV1Yvs7GG3zIM5Pnq",
	"CJrimFDGbPV2WD5RFxbxNCRDyazJuhZtNagHwnCzyIFdQtPUVqDYZtJA1jxrry0T/mJPjMlExrG8IMWZ",
	"9d7Zuia8Zzls01mSULWoAddeZJstRE6Cy1Iiq0IqBVKcoGLUnUrtpngxPA4qrbcCKyRbjJyCoCkPjoLH",
	"9iubzcys9zmY2VZf/8S/p2ARYaGyxyw4Cv4K5ud8yFIv7MPBYEMr4u1aEOcNxxo6EPtdPm4VeQ79mh8N",
	"jj59rnK30DWrXcgmOtWI19xtBp/x4gOLFKq3XF/yf0DxCXooJi+ENgpoQhikGNhEhN/vMWromGrYt65e",
	"AY1mvnJghXvv3WL/beY5dGSk2+4hRtHJhEc203o6eLzLntIVooQ0jrDNUn1fdxrrxDp/dOAbyK5VZ0S/",
	"L/2gsPZ2nzX4ohxy4F7Gchm2DszfyIMQ5NakXm2r28DldY11L8PgiaOiafKC2oNKp3t7yaP2S2pNyu1F",
	"j9svKlvDL2lAHRl9snlA8Plyydx18TCcrqhF8dVne26kGxTB7aX5RsEuuQNtfpJscdMiyrftLus5ZL7F",
	"uqQfj2568cYu/vlDgfl2JrqtGVCW280b6dZr6Lj6/rio5YSLeOEnqL5hpundCo11QZdfsSbiFT+2X1G8",
	"gaFFdS0gXtbd9+VuWFRoYYMCL3m2g985u3SiQVS8qtiv7PdVxa4p2JP1HYfdjKy/UzY/ab+ieA9DC5tz",
	"jizx2fGjjcvhWvSzlpODXZpqUQ75jcqmyXv/FUy7WLaL0OX7+XApm+o3vDytsg+gIaHC8Egf+eRd+lxe",
	"ycS6urFkC4vzqtl8Q0vkxkOFujq5PY1tg05S0vvHKylWvpXSKQDtRKsdQaz2HPTXHAtu0BAaY4Hjx9JO",
	"FIbabrGh6Na5EfYeF6NuHfe2j1z7FsZbxczVDqitmLnSA/XugWZeUQavWOV3bbDZd3W9Hdhcb328Y9hc",
	"NKxdVQ/fJPTGYHPO8DsFm7dylbvF2cIzfI3OL3vTjlC7agxtUNur0N2G2m2MXg+21/JysEsDv7Ngu10w",
	"2wGD8gXPu4Db66oNrwDBtw1gV4fg9R7FO4bgG3TdQ/AiBj1A8DUQvGPYKJtnbkThb8thXwEMX/ue7luF",
	"4fWmpK1AvNqW9O4hcVFVCK9flS/bsHjZavV20PhyQ+Id4/FKJ9lVPSl7qd4YJq+9S/gBle9g91tUFLhR",
	"/1ccbEdgXreMNmhe6tId3wdv5fd6eL6Bo4NdW/zd3RHvIKDtgENll+3Wgfr63m9XgOnbx7arA/XlPss7",
	"huobtd6D9XqF/ANcb9wx7xxPJGvD6nbE1wDTJdsxQvdNadvBuWtLewdxeS78QoXs51Y0LtmtAfGy0/Su",
	"MbjtGtwQjCW7SeQt2QPo3hnodnq6rNxV19gVZXuNbwXYqC13HVs3s3UDom7k3mA3pnuHIfQ6OWwJnCX7",
	"9jDzNhHoGnC57C69a6S8RqULkGzjyAM+XouPN7r+VLLNoHiIA74CTDyUbMfVI779bismdg147x4kTp3o",
	"vebYj22AeCjZLeHhsq32juGw7Y182dhi58bAcCrZAxbeERZOrYouaXXFHXYEwl7T23Aw6skdh8GNHF0P",
	"ghs5N9iFvd5dBLxGBNuF7aFk315txzYR5+r4t2zJvGP4u0abPfq1geMB/K4Dv5t8ve+auBH+nvhBXwEE",
	"zmnZMQyu9h1thcJl59G7B4d1qQpeoYqv2mCx76R6O9C43m14x/C4aBK7/tHfG4PJOb8foPKOoLIu1LZB",
	"45fcaEfYXLWENujs9eeOw+eNXF4Po9dycrBL2767kLpFLNvBgZxd3x683jZyXR1i1zvc7hhmb9B0D7WL",
	"4PMAt9fB7S7xougyuBF3/70Y9RUAb09MA/LufvEvXOwEr9c6PrYC9krPx7uH2C8qSuQVsvyuDbMXXSxv",
	"B7QvdfndMWovW3SuakjRpfLGcLtn+gNw3xFwvyh1t0nxl11xR+xes4g28F5o0R1H7y2sXo/f13NzsFsz",
	"v7sQvlU220ELz7Fdo/haU9Lrwfmtg9rV8fxSZ9cdA/pNmu8RfRmWHiD9OkjfFkk2ruaWsS+ccAZWlwMi",
	"iZgwmEMs07y5eabivD/q0cFBjANmUpujHwY/DKzR5USsTLWp6yjZy6wQAE0RJW9flOTeQeB7CiKSX9tz",
	"3vdgWfvWhmK2olvLxvlsEQ7ZQ0aCIge+lX0vjakAktBohuTv2+6gXJRtYSoLuTqezasUVfAbJypr5TfO",
	"Zl+d+p9//dt12jUy4RGpvHGk2t+fG11ZwJ66bJy6oaW/rr5mNqw2ng6r75gdiRdEczGNi07XXAqSyniR",
	"SJXOeESkqL4IoPaWiuek2nE/bwvvaC5VfCPh/nSo5G/tecJ8siIH3jhX0a+nT17GVGs+4aWW1d/t4t5Y",
	"lILyxD95PhI4bBRczKj5ThMujJ23B19SqYH9eRQQmjFuiHVeyCSOtqIvrC7POc0bJY8ERFIvtIGk55ZR",
	"ELt2zzOe6tC9iZj7tyYlkIxB4U819pXPS19+vvy/AAAA///eEz9TY7sAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
