//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for HealthStatus.
const (
	Ok HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Cluster defines model for Cluster.
type Cluster struct {
	// ApiEndpoint Kubernetes API server URL (informational).
	ApiEndpoint *string    `json:"api_endpoint,omitempty"`
	CreatedAt   *time.Time `json:"created_at,omitempty"`

	// DisplayName Human-friendly label, free-form.
	DisplayName *string `json:"display_name,omitempty"`

	// Environment Free-form environment tag (e.g., dev, staging, prod).
	Environment *string             `json:"environment,omitempty"`
	Id          *openapi_types.UUID `json:"id,omitempty"`

	// KubernetesVersion Cluster API server version reported by Kubernetes (e.g. "1.29.5").
	KubernetesVersion *string `json:"kubernetes_version,omitempty"`

	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`
	Name   string             `json:"name"`

	// Provider Underlying Kubernetes distribution or hosting provider.
	// Open-ended; common values: gke, eks, aks, openshift, rke, kubeadm, onprem, other.
	Provider  *string    `json:"provider,omitempty"`
	Region    *string    `json:"region,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// ClusterCreate defines model for ClusterCreate.
type ClusterCreate struct {
	// ApiEndpoint Kubernetes API server URL (informational).
	ApiEndpoint *string `json:"api_endpoint,omitempty"`

	// DisplayName Human-friendly label, free-form.
	DisplayName *string `json:"display_name,omitempty"`

	// Environment Free-form environment tag (e.g., dev, staging, prod).
	Environment *string `json:"environment,omitempty"`

	// KubernetesVersion Cluster API server version reported by Kubernetes (e.g. "1.29.5").
	KubernetesVersion *string `json:"kubernetes_version,omitempty"`

	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`

	// Name Stable slug-like identifier, unique across the CMDB.
	// Immutable after creation.
	Name string `json:"name"`

	// Provider Underlying Kubernetes distribution or hosting provider.
	// Open-ended; common values: gke, eks, aks, openshift, rke, kubeadm, onprem, other.
	Provider *string `json:"provider,omitempty"`
	Region   *string `json:"region,omitempty"`
}

// ClusterList Paged list of clusters.
type ClusterList struct {
	Items []Cluster `json:"items"`

	// NextCursor Opaque cursor to pass as `?cursor=` to fetch the next page.
	// Absent or null when no more pages remain.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// ClusterMutable Fields on a Cluster that clients may set and later update.
type ClusterMutable struct {
	// ApiEndpoint Kubernetes API server URL (informational).
	ApiEndpoint *string `json:"api_endpoint,omitempty"`

	// DisplayName Human-friendly label, free-form.
	DisplayName *string `json:"display_name,omitempty"`

	// Environment Free-form environment tag (e.g., dev, staging, prod).
	Environment *string `json:"environment,omitempty"`

	// KubernetesVersion Cluster API server version reported by Kubernetes (e.g. "1.29.5").
	KubernetesVersion *string `json:"kubernetes_version,omitempty"`

	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`

	// Provider Underlying Kubernetes distribution or hosting provider.
	// Open-ended; common values: gke, eks, aks, openshift, rke, kubeadm, onprem, other.
	Provider *string `json:"provider,omitempty"`
	Region   *string `json:"region,omitempty"`
}

// ClusterUpdate Fields on a Cluster that clients may set and later update.
type ClusterUpdate = ClusterMutable

// Health defines model for Health.
type Health struct {
	Status HealthStatus `json:"status"`

	// Version Build version of the running argosd.
	Version *string `json:"version,omitempty"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// Problem RFC 7807 problem details.
type Problem struct {
	Detail *string `json:"detail,omitempty"`

	// Errors Field-level validation errors, when applicable.
	Errors *[]struct {
		Field   string `json:"field"`
		Message string `json:"message"`
	} `json:"errors,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   int     `json:"status"`
	Title    string  `json:"title"`
	Type     string  `json:"type"`
}

// ClusterId defines model for ClusterId.
type ClusterId = openapi_types.UUID

// Cursor defines model for Cursor.
type Cursor = string

// Limit defines model for Limit.
type Limit = int

// BadRequest RFC 7807 problem details.
type BadRequest = Problem

// Conflict RFC 7807 problem details.
type Conflict = Problem

// NotFound RFC 7807 problem details.
type NotFound = Problem

// Unauthorized RFC 7807 problem details.
type Unauthorized = Problem

// ListClustersParams defines parameters for ListClusters.
type ListClustersParams struct {
	// Limit Maximum number of items to return. Server clamps to [1, 200].
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque cursor returned from a previous list response.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// CreateClusterJSONRequestBody defines body for CreateCluster for application/json ContentType.
type CreateClusterJSONRequestBody = ClusterCreate

// UpdateClusterApplicationMergePatchPlusJSONRequestBody defines body for UpdateCluster for application/merge-patch+json ContentType.
type UpdateClusterApplicationMergePatchPlusJSONRequestBody = ClusterUpdate

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Liveness probe
	// (GET /healthz)
	GetHealthz(w http.ResponseWriter, r *http.Request)
	// Readiness probe
	// (GET /readyz)
	GetReadyz(w http.ResponseWriter, r *http.Request)
	// List clusters
	// (GET /v1/clusters)
	ListClusters(w http.ResponseWriter, r *http.Request, params ListClustersParams)
	// Register a cluster
	// (POST /v1/clusters)
	CreateCluster(w http.ResponseWriter, r *http.Request)
	// Delete a cluster
	// (DELETE /v1/clusters/{id})
	DeleteCluster(w http.ResponseWriter, r *http.Request, id ClusterId)
	// Get a cluster
	// (GET /v1/clusters/{id})
	GetCluster(w http.ResponseWriter, r *http.Request, id ClusterId)
	// Update mutable fields of a cluster
	// (PATCH /v1/clusters/{id})
	UpdateCluster(w http.ResponseWriter, r *http.Request, id ClusterId)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReadyz operation middleware
func (siw *ServerInterfaceWrapper) GetReadyz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReadyz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListClusters operation middleware
func (siw *ServerInterfaceWrapper) ListClusters(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListClustersParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListClusters(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateCluster operation middleware
func (siw *ServerInterfaceWrapper) CreateCluster(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCluster(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteCluster operation middleware
func (siw *ServerInterfaceWrapper) DeleteCluster(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ClusterId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteCluster(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCluster operation middleware
func (siw *ServerInterfaceWrapper) GetCluster(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ClusterId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCluster(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateCluster operation middleware
func (siw *ServerInterfaceWrapper) UpdateCluster(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ClusterId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateCluster(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/healthz", wrapper.GetHealthz)
	m.HandleFunc("GET "+options.BaseURL+"/readyz", wrapper.GetReadyz)
	m.HandleFunc("GET "+options.BaseURL+"/v1/clusters", wrapper.ListClusters)
	m.HandleFunc("POST "+options.BaseURL+"/v1/clusters", wrapper.CreateCluster)
	m.HandleFunc("DELETE "+options.BaseURL+"/v1/clusters/{id}", wrapper.DeleteCluster)
	m.HandleFunc("GET "+options.BaseURL+"/v1/clusters/{id}", wrapper.GetCluster)
	m.HandleFunc("PATCH "+options.BaseURL+"/v1/clusters/{id}", wrapper.UpdateCluster)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8RZbXPbNhL+Kzu4frBT6sVO0jbq3Nw4TtN6Li8eu7n7YPliiFhKqECAAUC5qkf//WYB",
	"UiIlKnbb1P1iUySIXeyz++wL71hq8sJo1N6x0R0ruOU5erTh16kqnUd7JuiHQJdaWXhpNBuxS7QLtD3u",
	"nJxqFJDGpSAFai8zibbPEiZpacH9jCVM8xzZiEnBEmbxUyktCjbytsSEuXSGOScpmbE592zEyjKs9MuC",
	"3nLeSj1lq1XCTkvrjN3V6H3BP5UIaXgMFn1pSbHMmhw4FBYX0pQOlHQeLLrCaIdrHT+VaJcbJeMmrKlY",
	"zn99g3rqZ2z0/Oi4S7E3Mpd+V6+3/FeZlznoMp+gBZOB9Jg78KZSsg/RmJAqnhfhwdVRAsfD4fU+/VQQ",
	"1VRPYMZL5dno+TAhXUkkGx0P6ZfU8dfRWmupPU7RshXpXRsjQP6Siwv8VKILJ0mN9qjDJS8KJVNOhxoU",
	"1kwU5l//4uiEdw01vrKYsRH7x2DjVoP41A3O41tR6LaNFAGPAmwU3meEtNGZkumjalLLhFvpZ+RMFrUH",
	"57lHOMD+tJ+AKKN8BELjMKj6zvjXptTiMVW9QGdKmyJo4yEj6UGVD5qXfmas/A0fVZ230jmpp2AsSL3g",
	"SgqYILdowZs56n6IkWqfBrkEvZR6n7HR1edlVy+8LT2fKGSr5I4V1hRovYy+m1rkHsVH7ltMIrjHnpc5",
	"BuLh4r1Wy5p4tqI4IXrqYKF7X4tx2WKJb56F0Kt/HidEhB4t2ep/V7z327D34rr637u+GybfHK/q21+x",
	"DhllIf7k8VZN5r2KVBw0T5q2a0m6Xm9iJr9g6tnqehv4E/h3OUGr0aNb5wGLU0kXKEBq8DOE07evXsaw",
	"jktOg8QvCH+NwVaiCsvBqXLaU3KOjQyVQKkl5QyeWuPcRsuxPsvzKAd4RscJ5pFG98eaJX8hylsIhSM9",
	"AIJzvlSGi5hTouGBg8bbGo+m4d9I15GmzvkURcyOJqtfc5SA2lYOyat18QDQSHp1Bm4tX4aQwV/9x/RB",
	"ydwbKLhzwB3c/Cve++cN3c3Qp7OAG+0GBZ9if6xPJo5I21jQpVJwO0MN2kBuLIYlDizmXFZg0prgUQ+L",
	"mXDqXUjW1q39c+dIryUq4cBo4FCtBT/jHlIlyWaQ8yU49MC1AMXpcYzDXQx4IT+iFoWRugPJRjSenJ+B",
	"i8XFh4s3cCB1pA1pNFeHtPGG6azsIh0hXaH48mN3cP1U5lz3MitRC7UExSeoEsgsYo827rdj5fj5Nx0S",
	"UC+kNTrHrrO8rreCxjLwfLpOxrhIKD1PpZ4mUFgjDvu7EbojdL620ccFWidjDtwqBSqQGkas1oLFwliP",
	"AibLJvkFnWDMjvrHL/rPx2xblafHHaoEo0VYhZARmvMW3PeacIuP7UR6y+0SSoe250rK+iggroc5LgcL",
	"rkqMcLlKx6bIhsk2/l1Ys5ACO4L1gxZo1ZI2bxhDSBI4KWkRxeLMOE9L6n36Y/2+QN1DLVB8D6nJc6Mh",
	"aOZGMJ1jAjh3CXD6YwrUbiYzn4ClJ4QfF3kCRhcW6b+fhS0fgD0xZMT78ytX+4P8QwjMP567dgj8Ldop",
	"9gpOdDYxYtkHSuNQJ6EscMf3cENheAPSgawTFJkxl56cMa4CbhEUZh5Knc64nqIgu6wS9hNyRWfdTpxU",
	"3ZbhCjX1CVfMzBsUt7Hc3lB5WUol1tFhskDJttSaAOd2apzo35vsKjW6uLUuO3cEX7w+hW+/G34LVTkL",
	"Aj2XqiNvxQd0tctA1hrr9jB2T+ECFYSCNhAnxOVJzCtVSU1AUK9W58S27ABMp+gcneNT7Hi2ZZy4xeaF",
	"LittZ1ipnec6xXZF283zGx9YN4/PX7xoNo/USm63jwnz0ivsPFq80ehMGZ+Y0o8miuv5vZln6/jhaS0t",
	"2e8qdBJMSyv98pJir2pqQx9yUkbnj13J61p86E7YDomen8W+BaRzJQowpe+ZrDfhWlDDrkWoRk6qVit4",
	"xgiiIBiXw+HTNLweLvEmMlOgA1I3qrA59cz7IvZUlKE73PyHy59DHsqMhSdPTiiinjxJqJJ4++pluNtg",
	"3kaqdMBVHNCEftbPcKxP3l1ensElpu/K/FSZUsDB5bvTQ/hUciWzqj+EzPIcb42d98d6rH+eSbeO74Nh",
	"/6g/PCQa4nDL1Zyi3M1RoTcaUrNAwnA01gA9eCMXqJGKN03dPRcy/KJ4RReX3FT0eAO2bmlPLz68IrmX",
	"5cThp5KSfiXdwa1UCrgQ8M4ITOAdz9EVPMUE/mvsnOrgBM6NSILEkBfGumUdL/0S5lILqrmKgsDV3gTO",
	"irZJufVmankxo5pmSXUwKfNDCHzIjFLmFtbUc3Czr6++OaxwL/Oc22WrNuulqL2VaURwGyXYBWkDyDoQ",
	"KNdPjYtbnJyfsQZFswASBSLlTl5INmJPw63QosxCYAxmISX8RtdTDPUX8VY4yZlgI/Yj+p+qJVuDouPh",
	"8DPThd83VagSU8dQ4RLtQqYYXE3JBfZbIc5GV9dN6659LXgXmYlPHdFHPCa7ppcH5ITL5pHbIv+DlrpD",
	"B8LcauctcsoqBZUpOqX7B4J7PuEOD0OqtcjTWZ0Adqx3EYX93cYLZ6aOKRSy4C3PMpmGrvD58Oljjoka",
	"Smnjo2KfR/WiTRr7YF0cDequda87U+t7Wi9KWtPuPRXcZskgzndXyb0Lqwk1VXl/GerNXr7Dyvu6+VXC",
	"nkUtujZfaztojIHDK0f3v9KaOwY8G3Hp/FqJBn7rW9fUXxjXgVicEtVjhFgUoPMvjVh+aVtWA6lVu/bw",
	"tsTVDpBHX1p45yy6akCr2Rzxywy5qBz8jYnyOvqxi7O6Btd4q5b1BpthUPcXl846bPVoLkMvvbj/pfVX",
	"gbaPXWzmXunaWzocbYsqBndSrKIJFcaWru2Ar8L9pgO2HOHZ/rlB3FH0/4Q5nt3/0vrLQ9scUe37jJHs",
	"zfp7Dzx8TM9fd3N/hwl/RH+//X5fCtl8UKXkENr9jg+GjVmAw5xrL1M3qrt7Uzf71uQhxCdGLEMh0mz3",
	"OwYFnZPsNu5xrPF7yTbf6Pv1H/KAapryIOJ9FPeLConW8PzxOPCPe2zUe2tqRKngPk5sV1/thvnqmnw1",
	"DkCjk7eNRXlIgcAFKlOEKW7CSquqrnY0GChaMDPOj74bfjcMnl/psLPV53pFOCiDqah/SwmeMF2tPohX",
	"lSAVZ3uH4fWB936b2nz+r02zul79PwAA//+4GdMsIiEAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
