{{- if and .Values.metrics.enabled .Values.metrics.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "longue-vue-vm-collector.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "longue-vue-vm-collector.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metrics.service.type }}
  selector:
    {{- include "longue-vue-vm-collector.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
{{- end }}
