apiVersion: v1
kind: Service
metadata:
  name: longue-vue
  namespace: longue-vue-system
  labels:
    app.kubernetes.io/name: longue-vue
    app.kubernetes.io/component: daemon
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: longue-vue
    app.kubernetes.io/component: daemon
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
