{{- if and .Values.podDisruptionBudget.enabled (gt (int .Values.replicaCount) 1) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "longue-vue-collector.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "longue-vue-collector.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "longue-vue-collector.selectorLabels" . | nindent 6 }}
{{- end }}
