{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "argos.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "argos.labels" . | nindent 4 }}
type: Opaque
stringData:
  ARGOS_DATABASE_URL: {{ include "argos.databaseUrl" . | quote }}
  {{- if .Values.postgresql.enabled }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | quote }}
  {{- end }}
  {{- if .Values.argosd.bootstrapAdminPassword }}
  ARGOS_BOOTSTRAP_ADMIN_PASSWORD: {{ .Values.argosd.bootstrapAdminPassword | quote }}
  {{- end }}
  {{- if .Values.oidc.enabled }}
  ARGOS_OIDC_ISSUER: {{ .Values.oidc.issuer | quote }}
  ARGOS_OIDC_CLIENT_ID: {{ .Values.oidc.clientId | quote }}
  ARGOS_OIDC_CLIENT_SECRET: {{ .Values.oidc.clientSecret | quote }}
  ARGOS_OIDC_REDIRECT_URL: {{ .Values.oidc.redirectUrl | quote }}
  {{- if .Values.oidc.scopes }}
  ARGOS_OIDC_SCOPES: {{ .Values.oidc.scopes | quote }}
  {{- end }}
  {{- if .Values.oidc.label }}
  ARGOS_OIDC_LABEL: {{ .Values.oidc.label | quote }}
  {{- end }}
  {{- end }}
{{- end }}
