{{- if not .Values.upstream.caBundleConfigMap -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "longue-vue-ingest-gw.fullname" . }}-upstream-ca
  labels:
    {{- include "longue-vue-ingest-gw.labels" . | nindent 4 }}
data:
  ca.crt: |
{{ required "upstream.caBundle is required when upstream.caBundleConfigMap is empty" .Values.upstream.caBundle | indent 4 }}
{{- end }}
